### ISSUE TITLE
Problems with running the example model

### ISSUE THREAD

**Issue by thormeyc** [calliope-project/calliope#1]
The code has an error (ZeroDivisionError: float division by zero) while running the example model. The system information and the full error output as well as the proceeding are listed in the respective txt-files.

[System-information.txt](https://github.com/calliope-project/calliope/files/41778/System-information.txt)
[Traceback.txt](https://github.com/calliope-project/calliope/files/41779/Traceback.txt)
[Vorgehen.txt](https://github.com/calliope-project/calliope/files/41780/Vorgehen.txt)

**Comment by sjpfenninger** [comment]
Can you confirm whether 815e8d5 addresses this?

**Comment by sjpfenninger** [comment]
Fixed by 815e8d5
