### ISSUE TITLE
Add cost class selection to plots

### ISSUE THREAD

**Issue by GraemeHawker** [calliope-project/calliope#104]
Currently, if multiple cost classes are defined within a model this adds an additional dimension to the result set, and calling a plotting function (e.g. plot.capacity) fails gracefully, and the result must be explicitly subsetted to one cost class only.

If multiple cost classes are defined, the drop-down plot selector should have additional select options for those cost classes (or possibly a second selector), and should default to displaying e.g. the monetary cost class.

**Comment by sjpfenninger** [comment]
Will be addressed in #357
