### ISSUE TITLE
Piecewise linearisation

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#107]
Permit piecewise linear formulation of some constraints, e.g. characteristic technology performance curves.

**Comment by tomdeallycat** [comment]
Piecewise linearization for efficiency variation with level of output power is a good candidate for this, as mentioned in your example, Stefan. Output efficiency variation with state of charge of the storage in the Supply + Storage technology would be another very useful capability. Without it, I don't think we have a way to represent the result of changing "head" with water level in a hydropower reservoir and its significant impact on output power of the hydroelectric dam.
