### ISSUE TITLE
GIS integration

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#11]
For higher spatial resolution, the integration of building and network placement with maps. Location coordinates can be loaded from map, as well as any physical constraints to connecting any resource with demand. Output can also be loaded to map for spatial visualisation of results.

**Comment by brynpickering** [comment]
A more interactive alternative to Basemap for plotting transmission could be: https://github.com/jwass/mplleaflet

**Comment by sjpfenninger** [comment]
Also see #12 and #18

**Comment by sjpfenninger** [comment]
This will become easier when it's possible to load non-timeseries data from CSV, so we will not further work on it.
