### ISSUE TITLE
Graphical user interface

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#12]
Packaging Calliope in a way to allow non-technical users to test scenarios in it, perhaps a web-based interface?

**Comment by brynpickering** [comment]
This is being solved by others (see [Engage](https://engage.nrel.gov/)) and won't be a core component of the Calliope offering.

**Comment by ramaroesilva** [comment]
Curious to know what's the opinion of @brynpickering, @sjpfenninger and @FLomb about the Engage interface. 

I have to try it out myself but I'm asking this since I discussed just recently with a colleague about the possibility of developing a GUI for calliope.
