### ISSUE TITLE
Plot.capacity urban scale tutorial

### ISSUE THREAD

**Issue by AlexandreLab** [calliope-project/calliope#130]
Hello, 

I am currently going through the tutorials and I have noticed an issue when plotting the capacity in the urban scale model.  The N1 node is getting the capacities of the X3 node displayed, the  X1 the ones from the X2 and the X2 the ones from the X1. 

![image](https://user-images.githubusercontent.com/20833629/43469937-4017cf7a-94df-11e8-91fb-c8b928c56c42.png)

https://calliope.readthedocs.io/en/stable/user/tutorials_02_urban.html

I am using the last version of Calliope 0.6.3.

Any further details required let me know.
Alexandre

**Comment by brynpickering** [comment]
Thanks for spotting this! Fixed in commit d26c0d4
