### ISSUE TITLE
Time independent production of a carrier

### ISSUE THREAD

**Issue by smorgenthaler** [calliope-project/calliope#131]
Calliope will always meet the demand given in each timeslice and location.

I would like to have an option to let the model decide when to produce the total demand over the entire model period at a given location.

**Comment by brynpickering** [comment]
This will be possible with the `carrier_con` group constraint (#310), where you could set a total production of a specific carrier to be met by a tech (or group of techs or group of techs at certain locations), then in the model you can have demand for that carrier which is unlimited.

**Comment by brynpickering** [comment]
It would now be possible to make this work with custom math.

1. update the `system_balance` constraint `where` string to ignore the `carrier`+`node` combination that you want to have a whole-timeseries balance over.
2. Add a new constraint to balance that carrier at that node over the whole year.
