### ISSUE TITLE
Fix ruamel.yaml and Python 3.7 compatibility

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#139]
## Problem description

Raised by @jedbrown during our [JOSS review](https://github.com/openjournals/joss-reviews/issues/825):

> I notice the requirement ruamel.yaml<=0.15 which would allow 0.15.0, but not 0.15.1. Is that really intentional? I also notice that ruamel.yaml 0.15.0 is not compatible with Python-3.7 and that Calliope is not compatible with current ruamel.yaml (at least because it now returns a type that implements the dict interface, but is not an instance of dict).

## Steps to address the problem

* Determine API changes in ruamel.yaml since 0.15
* Update AttrDict to work with >0.15
* Possibly simplify or remove our comment pass-through ability to reduce the complexity of AttrDict internals

**Comment by brynpickering** [comment]
It's still recommended to pin ruamel.yaml to <=0.15.0 (https://pypi.org/project/ruamel.yaml/), so I guess that is why we've gone with it. Is there any reason for us to maintain compatibility with Python 3.7?

**Comment by jedbrown** [comment]
@brynpickering I read that as a recommendation to pin the version ("for production systems") instead of using an open-ended `<0.16` that would assume interface stability for all 0.15.x releases. I think it's weird (and possibly a mistake) to recommend `<=0.15.0` in the context where they are talking about a big incompatible change from the 0.14 series. Presumably `==0.15.0` would make more sense.

Python 3.7 is already default in rolling release Linux distros, Homebrew, and Anaconda, and will be in discrete releases sometime in the near future (Fedora 29 in October). You may be able to delay a few months, but you'll likely get lots more requests in the coming months.

**Comment by GiorgioBalestrieri** [comment]
Hi all, my two cents on this: as @jedbrown pointed out, it should be obvious that supporting the last Python release should always be a goal for an open source project.
Besides the fact that Pyhon 3.7 comes with several cool features (data classes, simplified interactive debugging...), let's not go back to "why should we support Python 3?", those positions did not age well.
This being said, I understand it might take a while and this has to be prioritized against other development efforts, but I  think it should definitely be on the roadmap, at least.
I've never contributed to Calliope (yet, hopefully) so I'm really just expressing an opinion here, I trust the devs to know what's best for the project.

**Comment by brynpickering** [comment]
Hi both, thanks for your comments! I agree that we should aim to stay up to date as far as is possible, but it hasn't been a priority. I also think we can push it for longer in not being a priority, especially if a. it causes dependency issues (I e. We would be moving quicker than our existing dependencies), and b. We are recommending users install it in an isolated conda environment. I'm aware that we will update to it in due course!

On this particular issue, looks like ruamel.yaml hasn't updated its pinning recommendation in a long while. But, it was this recommendation that led us to our existing pinning many months ago. Whether or not it should be `==` or `<=` is now something of a moot point.

Before we look to update to the latest ruamel.yaml, would we be better depending on PyYaml? We lose roundtrip parsing of comments, but perhaps gain a more robust package?

**Comment by sjpfenninger** [comment]
Done in 6aa6e12
