### ISSUE TITLE
Add Python 3.7 compatibility

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#155]
After reading through #139 and #154, I understood Python 3.7 compatibility is currently not given. I thought it would be helpful to track progress explicitly in this issue.

**Comment by brynpickering** [comment]
Thanks @timtroendle. I think we're just waiting on Pyomo at this point. Looks like they'll [get it into their 5.5.1 release](https://github.com/Pyomo/pyomo/issues/604)

**Comment by sjpfenninger** [comment]
This is actually done as of 6f4b9e2!
