### ISSUE TITLE
Limit the shared capacity of technologies based on land constraints

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#159]
## Problem description

I am working on a model in which land for renewable electricity is a limiting resource. As long as technologies are not competing for land, this can easily be implemented in Calliope using the `energy_cap_max` constraint per technology. But when two or more technologies are competing for the same amount of land, one would need a constraint to limit the shared relative capacity to 1. I believe this is currently not possible within Calliope.

The `group_share` feature is close to what I'd need, in particular the `energy_cap_max` constraint. But instead of limiting the capacity to the entire system (which the latter does), I would need a `shared_energy_cap_max` constraint that limits the shared capacity relatively to 1.

Does that make sense? Is that anything that can and should be implemented?

## Calliope version

0.6.3

**Comment by brynpickering** [comment]
If you wanted the shared capacity to be location-specific (which land share suggests) then you can use the 'available_area' constraint at a location level. You can find it being used in the [urban scale example](https://calliope.readthedocs.io/en/stable/user/tutorials_02_urban.html?highlight=available_area). This leads to capping the sum of the area, for all area consuming technologies, at a given location. Would that fit?

**Comment by timtroendle** [comment]
It seems like it would fit perfectly. Am I right in assuming that you are combining it with `resource_area_per_energy_cap` to limit area available for technologies?

Does that mean it is possible to define "capacity constraints" purely on an area basis? So can I simply define a `resource_area_per_energy_cap` for all technologies and an `available_area` for each location and the installable capacity will be followed implicitly?

This feature looks great, but it is hard to find: `available_area` is mentioned only in the urban scale example. Shall I give a stab at documenting it in the `Advanced functionality` section?

**Comment by timtroendle** [comment]
Alright, thanks. I will use it for my model, write some words about it, and then we can discuss whether that makes sense.

**Comment by timtroendle** [comment]
Unfortunately I cannot get this to work. I tried three things:

1) Built it into my model. It became infeasible.
2) Ran [ac10db](ac10db72a8b6b72223ef3fdad6a7c6f5d23807f7) of the cambridge-calliope model (which has the area constraint as well). I am receiving the same error.
3) Built a minimal model, see below. Adding a area footprint to the wind turbine makes the problem infeasible. Without the `problematic line` the model works.

<details>
<summary>Minimal model</summary>
<pre>
<code>
model:
    name: 'A toy model based on area constraint'
    timeseries_data_path: '../model/'
    subset_time: ['2017-01-01 00:00', '2017-01-01 02:00']
run:
    solver: gurobi
    solver_io: python
    mode: plan
techs:
    demand_electricity:
        essentials:
            name: 'Electricity demand'
            parent: demand
            carrier: electricity
        constraints:
            resource: file=electricity-demand.csv:AT
    wind_onshore:
        essentials:
            name: Onshore wind
            carrier: electricity
            parent: supply
        constraints:
            resource_area_per_energy_cap: 0.1 # problematic line
            energy_cap_max: inf
            resource: 0.20 # static capacity factor
            resource_unit: energy_per_cap
            lifetime: 20
        costs:
            monetary:
                interest_rate: 0.1
                energy_cap: 1456
locations:
    region1:
        techs:
            demand_electricity:
            wind_onshore:
        available_area: 1000000
</pre>
</code>
</details>

<br>

By running `calliope run toy-model.yaml --save_logs=logs` and using the `solver_io=lp` option I created an lp representation of the model, see below.

I believe the issue is that both the upper bound and lower bound of the resource area of the wind power plant are 0, see these lines from the lp representation:

```
r_l_resource_area_constraint(region1__wind_onshore)_:
+1 resource_area(region1__wind_onshore)
>= 0

r_u_resource_area_constraint(region1__wind_onshore)_:
+1 resource_area(region1__wind_onshore)
<= 0
```

This leads to the fact that no wind power can be built, and hence the problem becoming infeasible.

<details>
<summary>Full lp representation of the minimal model</summary>
<pre>
<code>
\* Source Pyomo model name=unknown *\

min 
obj:
+1 cost(monetary_region1__wind_onshore)

s.t.

c_e_system_balance_constraint(region1__electricity_2017_01_01_00_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_00_00_00)
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_00_00_00)
= 0

c_e_system_balance_constraint(region1__electricity_2017_01_01_01_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_01_00_00)
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_01_00_00)
= 0

c_e_system_balance_constraint(region1__electricity_2017_01_01_02_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_02_00_00)
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_02_00_00)
= 0

c_u_balance_supply_constraint(region1__wind_onshore_2017_01_01_00_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_00_00_00)
-0.20000000000000001 energy_cap(region1__wind_onshore)
<= 0

c_u_balance_supply_constraint(region1__wind_onshore_2017_01_01_01_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_01_00_00)
-0.20000000000000001 energy_cap(region1__wind_onshore)
<= 0

c_u_balance_supply_constraint(region1__wind_onshore_2017_01_01_02_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_02_00_00)
-0.20000000000000001 energy_cap(region1__wind_onshore)
<= 0

c_e_balance_demand_constraint(region1__demand_electricity_2017_01_01_00_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_00_00_00)
= -6315

c_e_balance_demand_constraint(region1__demand_electricity_2017_01_01_01_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_01_00_00)
= -6102

c_e_balance_demand_constraint(region1__demand_electricity_2017_01_01_02_00_00)_:
+1 carrier_con(region1__demand_electricity__electricity_2017_01_01_02_00_00)
= -5830

c_u_carrier_production_max_constraint(region1__wind_onshore__electricity_2017_01_01_00_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_00_00_00)
-1 energy_cap(region1__wind_onshore)
<= 0

c_u_carrier_production_max_constraint(region1__wind_onshore__electricity_2017_01_01_01_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_01_00_00)
-1 energy_cap(region1__wind_onshore)
<= 0

c_u_carrier_production_max_constraint(region1__wind_onshore__electricity_2017_01_01_02_00_00)_:
+1 carrier_prod(region1__wind_onshore__electricity_2017_01_01_02_00_00)
-1 energy_cap(region1__wind_onshore)
<= 0

c_u_carrier_consumption_max_constraint(region1__demand_electricity__electricity_2017_01_01_00_00_00)_:
-1 carrier_con(region1__demand_electricity__electricity_2017_01_01_00_00_00)
-1 energy_cap(region1__demand_electricity)
<= 0

c_u_carrier_consumption_max_constraint(region1__demand_electricity__electricity_2017_01_01_01_00_00)_:
-1 carrier_con(region1__demand_electricity__electricity_2017_01_01_01_00_00)
-1 energy_cap(region1__demand_electricity)
<= 0

c_u_carrier_consumption_max_constraint(region1__demand_electricity__electricity_2017_01_01_02_00_00)_:
-1 carrier_con(region1__demand_electricity__electricity_2017_01_01_02_00_00)
-1 energy_cap(region1__demand_electricity)
<= 0

c_e_cost_constraint(monetary_region1__wind_onshore)_:
+1 cost(monetary_region1__wind_onshore)
-1 cost_investment(monetary_region1__wind_onshore)
= 0

c_e_cost_investment_constraint(monetary_region1__wind_onshore)_:
+1 cost_investment(monetary_region1__wind_onshore)
-0.058568908790694055 energy_cap(region1__wind_onshore)
= 0

r_l_resource_area_constraint(region1__wind_onshore)_:
+1 resource_area(region1__wind_onshore)
>= 0

r_u_resource_area_constraint(region1__wind_onshore)_:
+1 resource_area(region1__wind_onshore)
<= 0

c_e_resource_area_per_energy_capacity_constraint(region1__wind_onshore)_:
-0.10000000000000001 energy_cap(region1__wind_onshore)
+1 resource_area(region1__wind_onshore)
= 0

c_u_resource_area_capacity_per_loc_constraint(region1)_:
+1 resource_area(region1__wind_onshore)
<= 1000000

c_e_ONE_VAR_CONSTANT: 
ONE_VAR_CONSTANT = 1.0

bounds
   0 <= energy_cap(region1__demand_electricity) <= +inf
   0 <= energy_cap(region1__wind_onshore) <= +inf
   0 <= carrier_prod(region1__wind_onshore__electricity_2017_01_01_00_00_00) <= +inf
   0 <= carrier_prod(region1__wind_onshore__electricity_2017_01_01_01_00_00) <= +inf
   0 <= carrier_prod(region1__wind_onshore__electricity_2017_01_01_02_00_00) <= +inf
    -inf <= carrier_con(region1__demand_electricity__electricity_2017_01_01_00_00_00) <= 0
    -inf <= carrier_con(region1__demand_electricity__electricity_2017_01_01_01_00_00) <= 0
    -inf <= carrier_con(region1__demand_electricity__electricity_2017_01_01_02_00_00) <= 0
    -inf <= cost(monetary_region1__wind_onshore) <= +inf
   0 <= resource_area(region1__wind_onshore) <= +inf
    -inf <= cost_investment(monetary_region1__wind_onshore) <= +inf
end
</pre>
</code>
</details>

<br>

@brynpickering  Do you know the commit of the version with which you ran the cambridge-calliope model? Would be interesting to see whether I can resolve my issue with that version and if yes, what has changed since.

**Comment by brynpickering** [comment]
Hi Tim, could you just try setting `resource_area_max` to `inf` for your wind power tech? I suspect it is an issue with the default value used for `resource_area`. I don't think the cambridge-calliope commit will help, as it is based on v0.6.2 (i.e. prior to the change in the way `resource_unit` works). The latest iteration of the urban scale example would likely be better.

**Comment by timtroendle** [comment]
That indeed solves the issue for the minimal model. And you are right, it seems the default for the upper bound for `resource-area` is 0. For example, I tried setting `resource_area_max: 2`, and the resulting lp constraint was:

```
r_u_resource_area_constraint(region1__wind_onshore)_:
+1 resource_area(region1__wind_onshore)
<= 2
```

Should the default rather be `inf` and not `0`?

**Comment by brynpickering** [comment]
yes, I reckon it should be. A relook at the defaults might be necessary, to make sure they all make sense (capacities upper = inf, capacities lower = 0, efficiencies = 1).

**Comment by sjpfenninger** [comment]
@timtroendle in #160 you say "Fixes parts of issue #159" -- I assume because documentation is lacking to show how this problem can be solved with `resource_area`, not because of additional functionality you lack?

**Comment by timtroendle** [comment]
That's true. Basically it solved a problem I had. Whether that's a fix is debatable. That's also why I called it a `change` and not a `fix` in the changelog over in the pull request.

**Comment by timtroendle** [comment]
Maybe it's useful to remove the `constraint` label and add the `documentation` label instead? If there is something left here, it's documentation -- as pointed out by @sjpfenninger above.

**Comment by brynpickering** [comment]
Yes, I just popped into this issue to work out why it was still open. Perhaps this would be best closed and a new issue reopened on the more general issue of defaults (which I think is the only outstanding issue here)?

**Comment by timtroendle** [comment]
The issues on default values already exist (#160 , #161 ). Outstanding here is the documentation: at the moment it is difficult to know this feature exists: one has to navigate to `Listing of configuration options` and then search for the right keyword.

Would it be reasonable to add the documentation of the feature to `Advanced functionality`?

**Comment by brynpickering** [comment]
Thanks for clarifying.  Your suggestion would be valid, given that we have put an explanation of the `group share` constraint, among others, in the `Advanced functionality` section. But perhaps that should be separated into `Advanced constraints` and `Advanced configuration` (or similar). 

That way, given that most constraints we add in the future may be considered _advanced_, there will be a clear place for them to reside.

**Comment by brynpickering** [comment]
@sjpfenninger what of this issue have you cleaned up in your latest PR (#214)?

**Comment by sjpfenninger** [comment]
What remains outstanding - documentation:

> Outstanding here is the documentation: at the moment it is difficult to know this feature exists: one has to navigate to Listing of configuration options and then search for the right keyword.
> 
> Would it be reasonable to add the documentation of the feature to Advanced functionality?
