### ISSUE TITLE
Add a guide for applied modelling strategies 

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#167]
Some things that would be handy to know for a modeller:

* Don't use excel to manage timeseries CSVs as it changes the datetime format automatically to match the device datetime format. A user might not realise this on saving the CSV and then come across lots of errors that they weren't expecting

* Ways to implement complex behaviour of technologies, e.g. buffering a resource, seasonal supply.

* Ways circumvent non-intuitive results caused by the combination of certain constraint, e.g. avoiding unphysical heat loss using storage techs / distribution links.

* How to use time clustering effectively to reduce a problem size, then use operation mode to check that the resulting capacities are sufficient

Below are edits as we get more things coming in that we would want to add:

* How to create a demand tech that has an amount to be met by the end of a certain time period, but it doesn't matter exactly which timesteps it does that in along the way. @pmmeyourmodel's solution: conversion -> storage -> demand, where the demand only has a finite value in the timestep(s) of interest (e.g. end of the year). Energy can be incrementally stored in the storage device, then dumped to meet demand in just the timestep(s) of interest.

* How to stop "heating up the environment" (see #268) by using a minimal cost applied to transmission, or by a complex system of conversion technologies and new carriers.

**Comment by sjpfenninger** [comment]
See #325

**Comment by lblabr** [comment]
where i may find:
 @pmmeyourmodel's solution: conversion -> storage -> demand, where the demand only has a finite value in the timestep(s) of interest (e.g. end of the year) ?

**Comment by brynpickering** [comment]
you can now solve this with the `carrier_con` based [group constraint](https://calliope.readthedocs.io/en/stable/user/advanced_constraints.html#group-constraints), for demands that need to be met by the end of the year, but are otherwise time agnostic.

**Comment by lblabr** [comment]
thanks a lot... i'm quit new to calliope, could you pls. explain  a little bit in  more detail ? so far, i'm not able to get transfer from the linked documentation, how to add that to an group constraint.

i would like to realize  an happy hour in the supply (supplier, from grid) (1hour per day / 19:00 -20:00) how to do that ?

**Comment by brynpickering** [comment]
I would recommend spending more time with the example models, and the [YAML files](https://calliope.readthedocs.io/en/stable/user/ref_example_models.html) describing them (including specific scenarios/overrides which implement group constraints). For specific implementation questions, you can ask on the [Gitter chat](https://gitter.im/calliope-project/calliope).

**Comment by lblabr** [comment]
ok, thanks a lot, i will ask on gitter
