### ISSUE TITLE
Limit the shared capacity across nodes but not globally

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#176]
## Problem description

Say you are having a model including several countries with subnational geographic resolution. Say you want to model national renewable targets, e.g. country X claiming to have 30% renewables in 2020. Say you are modelling the year 2020 ( and assuming the country will reach these targets) you would need a constraint making sure the total capacity of renewables in all sub-nodes of country X is equal to or above 30%.

As far as I can tell, this is not possible at the moment. It’s obviously possible on the node level, and it’s possible on the global/system level using the `group-share`  feature. For the example above you would need a `group-share` that is not global and not (node-)local, but something in between.

Am I wrong in that this is not possible at the moment? Would it be reasonable to add it as a feature?

## Calliope version

0.6.3

**Comment by timtroendle** [comment]
A workaround is to use location specific techs. But that workaround isn't error prone: because currently `group-shares` are always global, the constraining value must be global as well. So in my example above, it wouldn't be `30%`(of national capacity), but maybe something like `12.5%` (of global capacity). For that you need to know the ratio national / global capacity, which may not be known a priori (at least not in my case).

**Comment by sjpfenninger** [comment]
Implemented in #191
