### ISSUE TITLE
(Optionally) communicate non optimal solution through CLI

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#182]
## Problem description

I am using Calliope in an automated workflow. To me, a non-optimal solution is a fail and I would like my workflow to stop at that point. But because Calliope CLI returns a `0 / success` my workflow continues, which is ~~sub-optimal~~ not what I want. 

Calliope _could_ return a fail whenever the solution is non-optimal. Would it make sense to build that (potentially as an option) into the CLI?

## Calliope version

0.6.3

**Comment by brynpickering** [comment]
That would be a simple addition. At the moment we capture the termination condition to decide whether plots should be generated or not (if a user used `--save_plots`), it would just require a conditional for something like `--break-on-fail` to return a Calliope `ModelError` rather than returning `None`.

**Comment by timtroendle** [comment]
Yep and I could build it in. Just wanted to know whether you think it makes sense; for example is non-optimal = fail true? For me yes, but for others as well?

**Comment by timtroendle** [comment]
And should it be optional, or is it always a good idea?

**Comment by sjpfenninger** [comment]
I think non-optional = fail could be the default, with an option to turn it off.

**Comment by brynpickering** [comment]
Yeah, you might like your automated runs to keep going and have the lack of optimality caught later down the line (given that we include in the model attributes using `termination_condition` whether it was optimal or not). But, as Pyomo gives no useful information back for a non-optimal run, I agree that the default should probably be fail.

**Comment by timtroendle** [comment]
Implementation hint (for myself): looks like the `click` way of doing this is to raise an exception: https://stackoverflow.com/a/26247420/1856079.
