### ISSUE TITLE
Fragility when using override_dict to import new scenario YAML file

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#186]
## Problem description

If you want to load a scenario YAML file in using an override dict, you a. have to define it as a YAML string (not as a python dictionary) and b. have to specify the absolute path to the file, if you are initialising the model from a different location to where the file is found.

Forcing use of YAML string makes things cumbersome when you want the override dict to include multiple overrides.

When loading from YAML string, it seems that `calliope.attrdict.from_yaml_string` cannot access the base path, which would be needed when resolving imports, to allow you to define the scenario YAML relative to the model YAML location.

## Steps to reproduce the problem

Both of the following will fail to load a previously undefined scenario YAML file. The second case would also fail in the CLI:

```
m = calliope.Model('model.yaml', scenario=scenario_001, override_dict: {'import': ['new_scenarios.yaml']})
```

```
m = calliope.Model('path/to/model.yaml', scenario=scenario_001, override_dict: "import: ['new_scenarios.yaml']")
```
## Calliope version
0.6.3

**Comment by sjpfenninger** [comment]
Tracking this in #326, which should resolve the issue once complete.
