### ISSUE TITLE
Support for mixed integer (MILP) constraints

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#2]

**Comment by brynpickering** [comment]
Added in commit 6f66065 
Binary variables seem to be possible for GLPK to handle, integer variables lead to no model convergence. CPLEX or similar seem to handle them just fine.

**Comment by sjpfenninger** [comment]
We'll need some docs to explain/disentangle `e_cap.*`, `s_cap.*`, `unit_cap.*`, `e_cap_per_unit`, `s_cap_per_unit`, `purchase`

**Comment by sjpfenninger** [comment]
Also possibly should `unit_cap` have a different name to make the difference to `e_cap` et al clearer - one is int, the other float. Maybe `units`?

**Comment by brynpickering** [comment]
Agreed on documentation. I guess we could have `units.max` etc. and that would work

**Comment by brynpickering** [comment]
I've updated to `units` and will work on documentation before committing

**Comment by brynpickering** [comment]
This has been included in Calliope (inc. documentation) since v0.5.3
