### ISSUE TITLE
Document and log automatically derived distances

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#209]
## Problem description

Calliope can automatically derive distances between two locations if both locations have coordinates. This mechanism is very practical, but not properly documented. Issues are:

* Coordinates can be given in lat/long _or_ with cartesian coordinates on a 2d plane. The latter is not documented.
* When coordinates are given in lat/long, the resulting distance is given in meters. That is not documented.
* There is no way of checking whether the result is as expected. An easy solution would be to log the calculated total distance: "Calliope derived a total link length of 25000 km."
* Kilometers would be a better unit than meters. It is more intuitive to me, even in an urban model. But for national or continental scale models, there is also a numerical issue:

```Python
In [1]: 0.99999995**100000 # 100 km high voltage ac transmission
Out[1]: 0.995012479065401 # noise starts in e-5

In [2]: 0.99999995**10000000 # 1000 km high voltage ac transmission
Out[2]: 0.9512294232839076 # noise starts in e-3
```

## Calliope version

0.6.4.dev

**Comment by brynpickering** [comment]
I was about to say that "the distances are stored in `model_data`", but I see that they're not... Perhaps we could populate a variable with those values?

Units, agreed, should be better communicated. I have a preference for them being included as attributes in `model_data`, but that might not work where there are some variables in there with dimensions which have different units (`costs`, for instance).

km would probably be better, particularly at the distances you are considering. If you know the distances, you can set them yourself, as a technology-specific override within a link.

**Comment by sjpfenninger** [comment]
@timtroendle PRs are welcome!

**Comment by brynpickering** [comment]
`distance` is now in model data and only cartesian coordinates are allowed (x/y wasn't worth including for the maintenance burden it entails). If any distances are derived from coordinates, there is a log output at the `DEBUG` level to notify users. The actual numbers aren't provided, but that can be checked in the distance matrix in `model.inputs`.

Only thing that needs dealing with is distance units. We probably need a `config.init` parameter to set the unit. My concern is that a user might provide distances for some links in metres/km and then we derive distances in km/metres in the same matrix and mess things up. A config param will make it explicit.
