### ISSUE TITLE
Handling of storage and transmission techs in levelised cost

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#210]
## Problem description

This is not exactly a problem, but rather a definition issue: Calliope considers generation of storages when calculating `systemwide_levelised_cost` --- personally, I would not. For the per technology level, levelised cost may be interesting. But for the total levelised cost (i.e. all locs and techs),  you'd want to know the costs of actually generated energy, i.e. the amount of energy that equals energy demand excluding storage and losses. At least I would.

Maybe this has been discussed already and there has been a decision to do it the way it is currently done? If yes, maybe there could be a second `systemwide_levelised_cost_net_energy` or so?

## Calliope version

0.6.4.dev

**Comment by brynpickering** [comment]
Agreed that excluding storage and transmission would seem to make the most sense (or, like with the group share constraints, having the ability to either specify `demand` or `supply`?). With the two of them in at the moment, it will be double counting: energy production to charge storage and energy production on discharging the storage (similarly for transmission). Not sure it was a conscious decision to include those two tech types.

**Comment by timtroendle** [comment]
I tried to implement this, but failed because I do not understand where the information about the type of technology is stored. I found some sets, but not for supply technologies.

I also found `model._backend_model.loc_tech_carriers_supply_all` but that's not available in the function and it feels brittle to rely on the backend here.

Any hints on how to properly filter technologies?

**Comment by timtroendle** [comment]
Found it. 🎉
