### ISSUE TITLE
Storages with fixed energy to power ratio

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#212]
## Problem description

Currently, storages _always_ have two independent decision variables: `energy_cap` and `storage_cap`. The currently existing `charge_rate` constraint can cap the `energy_cap` based on `storage_cap`, but as long as the `charge_rate` is not 0, the two variables remain largely independent.

There are situations where one would want to tightly link the two variables:

* technological reasons: one may want to assume that batteries can only have a certain energy/power ratio;
* economic reasons: one may know or assume costs per installed power ( or per installed energy ) but only based on a certain energy/power ratio of the storage technology ([example](https://doi.org/10.1038%2Fnenergy.2017.110)).

This is currently impossible.

## Calliope version

0.6.4.dev

**Comment by brynpickering** [comment]
I would argue that the current implementation of charge rate (or C-rate, using terminology from your example) is correct. In your examples, although there are given energy/power ratios for storage technologies, these give the maximum, do they not? Any energy technology that can have a discharge rate of 50% of the maximum stored volume should also be able to discharge at a 25% rate. For batteries, C-rate is calculated based on maximum current draw, but clearly it is possible for the current draw to fluctuate based on the load, provided it doesn't go above the maximum.

Still, there are probably cases where you don't want this to apply, even if it is somewhat unphysical (similar to my use of not allowing PV curtailment at the urban scale ;) ).

**Comment by timtroendle** [comment]
I'm not saying the current implementation of `charge_rate` is wrong. But it cannot do what I am requesting above. I would agree with what you are saying about charge rates, but remember this here is not about currents and powers, but this is about _installed_ power (energy cap).

So as an example for batteries: if you are installing fictional battery type Li-Ion X2000 (which as we all know has a max charge rate of 1) you may want to constrain the charge rate for whatever reason to 0.5, and you can do so using the current `charge_rate` parameter. But don't forget, the battery actually has a max charge rate of 1, so while you are using only 0.5 kW of the installed 1 kWh, you still have installed 1 kW. That cannot be modelled with `charge_rate`.

A related example of pumped hydro: Iain's paper I linked above does give you costs for pumped hydro (and other types of storages), but it doesn't give you costs separated into costs for installed power and costs for installed storage capacity (which, I believe isn't possible anyways because the costs are not orthogonal). So it gives you pumped hydro costs as 1500€/kW (or whatever). Now as long as you do not tightly link storage capacity to energy capacity in Calliope, Calliope can and will build storage capacity free of charge.

**Comment by timtroendle** [comment]
Just to capture what @brynpickering, @sjpfenninger, and I just discussed:

* the constraint I am proposing here should be called `energy_cap_per_storage_cap_equals`
* the former `charge_rate` should be called `energy_cap_per_storage_cap_max`
* `charge_rate` remains but with a FutureWarning that it will be dropped in 0.7.0
