### ISSUE TITLE
Is a resource value of '0' finite, and should it be the default?

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#220]
## Problem description

Currently, `resource` default is 0. Would it make more sense to be `inf`?

When it is zero, it does not get added to the set `loc_techs_finite_resource`, since a condition for that is `if loc_techs_config[k].constraints.get('resource')`. Is this expected behaviour?

## Calliope version

0.6.3-dev

**Comment by sjpfenninger** [comment]
Tracked in #326
