### ISSUE TITLE
Limit group constraint demand_share to actual demand

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#227]
## Problem description

Currently, the group constraint `demand_share` relates the generation of the declared technologies to the _total_ consumption, i.e. including storage consumption and exports. That's at least confusing. I believe there should either (A) be an option to explicitly limit the consumption technologies, or (B) it should always use only demand technologies.

(B) is more intuitive and consistent with the documentation and name, what one needs to model renewable shares or import restrictions, and easier to implement. 

## Calliope version

0.6.4.dev

**Comment by timtroendle** [comment]
I can provide a PR next week. @sjpfenninger @brynpickering could you let me know if you object to implementing (B)?

**Comment by brynpickering** [comment]
👍 I'm surprised B isn't how it was already implemented...

**Comment by timtroendle** [comment]
Probably rather a bug than a feature. 😬

**Comment by timtroendle** [comment]
Here's a nasty detail why this is rather a bug than a feature: I created a regression test with two locations and a link in between. What the current implementation of the demand share group constraint does is artificially increasing the consumption of the links, so that it overcomes the demand share constraint.

In numbers: the supply was restricted to 72, but the cheapest option would be to have a supply of 360. So, the found solution created a consumption of the transmission line of 560 so as to allow the supply of 360. The _net_ consumption of the line was -180. So Calliope simply made up 740 gross transmission. 

Not quite sure my explanation was clear enough. But it's certainly nasty, and likely not what a user would want or expect.
