### ISSUE TITLE
Validate models against YAML schema

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#230]
Rather than piecemeal validation as partially implemented e.g. in #219, validate models against a complete YAML schema.

**Comment by timtroendle** [comment]
To add some details to this. This may bring the following benefits:

1. Cleaner Calliope code.
2. Robust error detection (I personally still often run into situations where my mistakes remain undetected).
3. Standard way of validation, meaning that you can use any tool to validate models. In particular, this will allow you to have online validation, auto-correction, and tab-completion in your IDE/editor.

The third may likely not work with Calliope's `import` mechanism. But it seems, [there is no standard way of doing this](https://stackoverflow.com/a/15437697/1856079).

**Comment by sjpfenninger** [comment]
Closing as this being worked on now with https://github.com/calliope-project/typedconfig

**Comment by brynpickering** [comment]
Introduced in #518
