### ISSUE TITLE
Replacement of a component

### ISSUE THREAD

**Issue by darlainedeme** [calliope-project/calliope#242]
## Problem description

Hi everybody. Is there a way to take into account the replacement of components having lower lifetime than the other ones? I'm developing a model with several off-grid mini-grids and considering the replacement of components like the storage is definitely paramount.
Thank you in advance!

**Comment by sjpfenninger** [comment]
A proxy for this already exists in how we deal with the effect of lifetime on costs -- the capacity cost of technologies with shorter lifetimes will be amplified relative to those of technologies with longer lifetimes in the objective function.

**Comment by sjpfenninger** [comment]
We can do this in fancier ways once #125 is available.

**Comment by brynpickering** [comment]
This is now available within the downstream project https://github.com/calliope-project/calliope-pathways.
