### ISSUE TITLE
Tutorials in docs missing sidebar

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#244]
## Problem description

Most pages in the docs have a sidebar, e.g. the tutorials main page:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/17178478/58463838-e1e9f700-8134-11e9-8bbb-69a23eb24681.png">

This is not the case for the tutorials themselves, e.g.:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/17178478/58463911-0219b600-8135-11e9-8bc8-70460f2fae60.png">

This means you can't navigate easily from the tutorials to elsewhere in the docs (without going back). It's probably an issue caused by the docs being custom-built with an embedded Jupyter notebook.

## Calliope version

0.6.4

**Comment by sjpfenninger** [comment]
Fixed in 0f716f71
