### ISSUE TITLE
save_commented_model_yaml fails with cryptic error message

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#245]
## Problem description

When trying to generate a fill YAML model description from model results, `model.save_commented_model_yaml()` fails with a cryptic `AttributeError: 'NoneType' object has no attribute 'copy'` error message. I assume it's because `model_run` doesn't exist at this point, but that's an implementation detail.

I think having a full model description, potentially months or years after actually running the model, is highly valuable. The netcdf file is great for timeseries but not good for the model description. If the `model_run` cannot be regenerated, maybe it can be stored completely within the netcdf? I used to do that in the past: our model results were stored in a HDF5 file, and we copied the full model configuration as a varstring in a 1x1 array. Maybe not the most elegant solution, but absolutely fulfilled its job.

If the YAML cannot be regenerated or stored, I think there should be a clear error message: first, this is normal and simply cannot be done at this point. Second, pointing the user to a working way of understanding the model that is at the bottom of the model results.

## Steps to reproduce the problem

```Python
import calliope
model = calliope.read_netcdf("my-model-results.nc")
model.save_commented_model_yaml("full-model.yaml")
```

## Calliope version

0.6.4.dev

**Comment by sjpfenninger** [comment]
Fixed in #247
