### ISSUE TITLE
Ensuring all group constraints are tested

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#259]
## Problem description
As of commit 431ddacc1141b7268e12a7348b7a935b1dde15ae, the way in which group constraints are tested has been updated, to try and comprehensively cover all technology types that are available for use in each group constraint.

There are a load of group constraint tests from the 0.6.4 release that are currently being ignored, since they don't fit with the new testing structure. These need to be dealt with prior to releasing 0.6.5!

The new structure is to have a base model for all group constraints, onto which constraint specific override files are prepared, including scenarios which will test that the constraint builds with all allowed technology groups and that the results of optimisation when including all technology groups fits as expected. On top of that, there is a file in which the expected `loc_tech` sets, `model_data` variables, and pyomo constraints for each scenario are listed, so they can be used to verify that everything is working as expected.  

To do:

- [x] energy_cap_min/max
- [x] energy_cap_share_min/max
- [ ] resource_area_min/max/equals
- [ ] supply_share_min/max/equals
- [ ] demand_share_min/max/equals
- [ ] demand_share_per_timestep_min/max/equals/decision
- [ ] cost_min/max/equals
- [ ] cost_var_min/max/equals
- [ ] cost_investment_min/max/equals

## Calliope version
0.6.4-dev

**Comment by timtroendle** [comment]
We plan to remove group constraints in favour of custom constraints #100 .
