### ISSUE TITLE
Updating run configuration options on backend rerun

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#262]
## Problem description

Currently, if you want to use `model.backend.rerun()` with updated run configuration options (e.g. solver, warmstart, location to save logs) then you need to update `model.run_config`. This isn't particularly intuitive, since it is affecting the model options globally, not just specifically to the rerun of the backend. Ideally, these run configuration options could be overriden as arguments at rerun, e.g. `model.backend.rerun(solver='cplex')`.

## Calliope version

0.6.5-dev 634ffd4c0db5e60ea0592270bc02a7f514442341

**Comment by sjpfenninger** [comment]
Closing as tracked in #293
