### ISSUE TITLE
Utility function appears in documentation of group constraints

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#269]
## Problem description

The internal function `get_demand_share_lhs_and_rhs_loc_tech_carriers` appears in the documentation of the group constraints. 

I guess it should not be there.

## Calliope version

0.6.5-dev

**Comment by timtroendle** [comment]
https://calliope.readthedocs.io/en/latest/user/ref_formulation.html#calliope.backend.pyomo.constraints.group.get_demand_share_lhs_and_rhs_loc_tech_carriers

**Comment by sjpfenninger** [comment]
If custom constraints work, we'll get rid of group constraints, so this will not be an issue.
