### ISSUE TITLE
Clean up option_getter

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#27]
`option_getter` should include:

* `cost_getter`
* `cost_per_distance_getter`
* `any_option_getter`
* `depreciation_getter`

**Comment by brynpickering** [comment]
there's also `any_option_getter' and if we remove those wrappers we then open it up to including:

- `get_name'
- `get_carrier'
- `get_weight'
- `get_color'
- `get_source_carrier'
- `get_parent'
- `get_eff_ref'

**Comment by brynpickering** [comment]
I wonder whether a general `get` class or module might be useful? All the `get` functions could be kept in a subclass of Model, or standalone in `get.py`

**Comment by sjpfenninger** [comment]
Superseded by changes in 0.6.0
