### ISSUE TITLE
Solver output is logged twice to console

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#272]
## Problem description

The solver output is logged twice to console: one time with DEBUG level, one time with INFO level. See below. 

All Calliope logs before and after the solver output are just fine and on INFO level only.

```
[2019-07-24 16:28:02] DEBUG    Academic license - for non-commercial use only
[2019-07-24 16:28:02] INFO     Academic license - for non-commercial use only
[2019-07-24 16:28:05] DEBUG    Parameter OutputFlag unchanged
[2019-07-24 16:28:05] INFO     Parameter OutputFlag unchanged
[2019-07-24 16:28:05] DEBUG    Value: 1  Min: 0  Max: 1  Default: 1
[2019-07-24 16:28:05] INFO        Value: 1  Min: 0  Max: 1  Default: 1
[2019-07-24 16:28:05] DEBUG    Changed value of parameter LogFile to /var/folders/77/hl9n2z_n6059xs8ml53n_tsr0000gp/T/tmp8uah5hc7.log
[2019-07-24 16:28:05] INFO     Changed value of parameter LogFile to /var/folders/77/hl9n2z_n6059xs8ml53n_tsr0000gp/T/tmp8uah5hc7.log
[2019-07-24 16:28:05] DEBUG    Prev: gurobi.log  Default:
[2019-07-24 16:28:05] INFO        Prev: gurobi.log  Default:
```

## Steps to reproduce the problem

Run any model.

## Calliope version

0.6.5-dev

**Comment by timtroendle** [comment]
I looked into this because it's quite annoying. This is a regression likely introduced in #248 .

Also, this is a Gurobi only problem. I tried to fix it but didn't find a way so far. Unfortunately, it seems this in fact is based on some design decisions in the Gurobi Python library. Others have similar problems:

https://groups.google.com/forum/#!msg/gurobi/sV7xxN_mzCk/PNMPNMRGCQAJ

**Comment by timtroendle** [comment]
Here's a WIP solution:

https://github.com/timtroendle/calliope/commit/14ee95d73a55a6072cc0c8c55c2df0c6f495adce

**Comment by brynpickering** [comment]
Is this specific to using gurobipy as the interface? I imagine it wouldn't cause a problem if you didn't use the python interface.

To make it perform similarly to the other solvers, could we suppress all gurobipy outputs that are below the warning/error level? If you directly access their logger ('gurobipy') it should be possible to do that, right?

**Comment by timtroendle** [comment]
It's certainly not an issue with CBC, and it's weird enough that I think it may a gurobi issue only.

> To make it perform similarly to the other solvers, could we suppress all gurobipy outputs that are below the warning/error level? If you directly access their logger ('gurobipy') it should be possible to do that, right?

Agree that this would be the more consistent solution, but I didn't manage to get it to work. It may be because their logging configuration is hard coded and thus comes after me messing around with it.  Or it may be that I simply did the wrong things. Definitely not a Python logging expert, but I thought the solution should be a simple:

```Python
logger.Logger("gurobipy").setLevel("ERROR")
```

But no, this did not work.

**Comment by brynpickering** [comment]
> It's certainly not an issue with CBC, and it's weird enough that I think it may a gurobi issue only

Yeah, it's just the fact that gurobi is the only solver which can use its own python package to solve, allowing frictionless transfer of the optimisation problem from pyomo to the gurobi solver. The others require dumping the LP problem, then having the solver load the LP and solve it independently of a Python script.

We don't touch the gurobipy package, it's pyomo that loads it (see `solvers/plugins/solvers/gurobi_direct.py`). I'm also no logging expert, but it might be possible to directly point to the logger generated in that script and try to suppress it.

I'll do some tests and see if I can come up with anything of use...

**Comment by brynpickering** [comment]
Looks like this should work (placed after pyomo has been loaded, i.e. in `calliope/backend/pyomo/model.py`):

``logging.getLogger('gurobipy').setLevel(logging.ERROR)``

**Comment by timtroendle** [comment]
Thanks, that works. Quoting the Python doc here to understand why your line works and mine did not:

> Note that Loggers should NEVER be instantiated directly, but always through the module-level function logging.getLogger(name). Multiple calls to getLogger() with the same name will always return a reference to the same Logger object.

**Comment by sjpfenninger** [comment]
Thanks @timtroendle for figuring this out and fixing it! 🥇

**Comment by sjpfenninger** [comment]
And thanks to @brynpickering for discovering the underlying reason! 🥇🥇 ;)
