### ISSUE TITLE
Transmission techs in group constraints

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#273]
## Problem description

Transmission techs currently cannot be explicitly included to group constraints. They can, however, added implicitly by not mentioning any technology. See discussion in #271. For a constraint like "net import share" this is a problem, because an error is raised when transmission technologies are added explicitly.

Instead, for "net import share", one must not mention any technology. Unfortunately this raises a warning at the moment.

The cleanest solution to me would be the ability of Calliope to add transmission technologies to group constraints explicitly.

## Calliope version

0.6.5-dev

**Comment by sjpfenninger** [comment]
This will be taken care of by #324
