### ISSUE TITLE
Adding dynamic prices via national grid import

### ISSUE THREAD

**Issue by CROdominik** [calliope-project/calliope#280]
## Problem description
Currently, when modelling national grid import to any community-scale energy system, island or city, it seems that only fixed price from the national grid can be modelled. However, that is problematic as usually one needs to model the prices from day-ahead markets (that change hourly). It seems that om_prod cannot be defined from file that would give hourly prices. This is a big setback for any kind of energy systems that are not modelled as working in an island mode.

If I enter om_prod via a file that would give one value for each timestep, I get the following error:
TypeError: can't multiply sequence by non-int of type 'float'

If I use om_prod as a constant, everything works fine.

## Steps to reproduce the problem

Run any model where import from outside of system boundaries is modelled. I modelled grid import using parent: supply and giving prices via om_prod constraint. If om_prod is changing hourly, the Calliope cannot handle it.

## Calliope version

0.6.4.

**Comment by brynpickering** [comment]
Could you provide a snippet of the lines in the YAML file which you use to point to timeseries data for om_prod?

**Comment by CROdominik** [comment]
Sure,
1)     X7: # Crikvenica national grid connection
        techs:
            supply_grid_power_Crikvenica:
                costs:
                    monetary:
                        om_prod: file = Cropex_DA_halfhourly_prices.csv #cropex half hourly prices for 2017. interpolated half hourly values from hourly ones

The csv. file is in the same form  as for wind generation data, which works perfectly fine when defined in different timesteps as resource constraint.

2) 

  | X6 | X7
01-01-17 0:00 | 0.0618 | 0.0618
01-01-17 0:30 | 0.059825 | 0.059825
01-01-17 1:00 | 0.05785 | 0.05785
01-01-17 1:30 | 0.053335 | 0.053335

I'm using half-hourly resolution for the case study.*

**Comment by brynpickering** [comment]
OK, it is caused by the spaces around '=' in the yaml file. I suppose we should be more explicit about that requirement. I'll create another issue about addressing it in our documentation.

i.e.:
```
X7: # Crikvenica national grid connection
 techs:
     supply_grid_power_Crikvenica:
         costs:
             monetary:
                 om_prod: file=Cropex_DA_halfhourly_prices.csv
```

**Comment by CROdominik** [comment]
Confirmed, tested and working. Thank you!
