### ISSUE TITLE
Exception on using spaces either side of '=' when referring to timeseries files in YAML

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#281]
## Problem description

in our YAML files, we can only handle loading timeseries data if the data is formatted as e.g.:

`resource: file=filename.csv` or `resource: file=filename.csv:columnname`.

Referencing the file as follows will cause the data to be loaded in as a string without a timeseries dimension (and an exception will be raised on running the model):

`resource: file = filename.csv` or `resource: file = filename.csv:columnname`.

So, we need to either catch this use case during preprocessing checks, or be more explicit about the required formatting in the [documentation](https://calliope.readthedocs.io/en/stable/user/building.html#configuration-timeseries).

## Calliope version

0.6.4 / 0.6.5dev0

**Comment by sjpfenninger** [comment]
Will be solved in #326
