### ISSUE TITLE
Operational mode not fixing system capacities

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#29]
Calliope currently defines a number of capacities: `s_cap`, `e_cap`, `r_cap`, `rb_cap`, `r_area`. These are decision variables in planning mode. However, they *shouldn't* be decision variables in operational mode. Currently, there is no change in the constraint generation except that if a `.max` constraint is given for a capacity, it will be converted to `.equals` in operational mode, essentially setting it as a parameter. 
This means that any capacity given as 'inf' can be changed on each iteration of the rolling horizon. When cost is associated with the capacity, this will be different in each time step (when it should be constant).

In operational mode, the user shouldn't be allowed to define capacity costs unless they have also defined a `.equals` or `.max` for that capacity. The ideal case would be that there is a completely different constraint set which removes all capacities as decision variables, having them as parameters instead. But, this still requires that the user has defined `.equals` or `.max` for every capacity they want to cost. There's no issue with having an infinite capacity limit, provided there is no cost related to it.

An alternative is to consider *only* operational costs in operational mode, so all capacity costs are ignored. This makes sense from a minimisation perspective, the technologies can be assumed already purchased so their depreciated and time-weighted capacity costs should not affect the objective. 

Raising as issue to discuss best method for addressing. My vote is removing all capacity costs, meaning the user need not define `.equals` or `.max` for every capacity and all capacities can be removed as decision variables (set as parameters instead).

**Comment by sjpfenninger** [comment]
Fixed in 0.6.0
