### ISSUE TITLE
Rerun model misses run information

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#291]
## Problem description

A rerun model inherits _all_ attributes from the original model. This is problematic because the attributes contains information from the solver which is run specific.

## Steps to reproduce the problem

```Python
import calliope
model = calliope.examples.national_scale()
model.run()

new_results = model.backend.rerun()
assert new_results.results.time_finished != model.results.time_finished # fails
```

## Calliope version

0.6.5.dev (bcb56107bf3664c7ba38c6d2eca7bb72e393a2a5)

**Comment by brynpickering** [comment]
See #293
