### ISSUE TITLE
Rerun model cannot be saved as NetCDF4

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#292]
## Problem description

A rerun model cannot be saved as NetCDF4. The error message is `ValueError: unsupported dtype for netCDF4 variable: bool`, which is thrown somewhere in xarray's netcdf backend.

Potentially related to #282.

## Steps to reproduce the problem

```Python
import calliope
model = calliope.examples.national_scale()
model.run()
model.to_netcdf("test-orig.nc") # works

new_results = model.backend.rerun()
new_results.to_netcdf("test.nc") # fails
```

## Calliope version

0.6.5.dev (bcb56107bf3664c7ba38c6d2eca7bb72e393a2a5)

**Comment by timtroendle** [comment]
A workaround to store at least results is to literally do that:

```Python
new_results = model.backend.rerun()
new_results.to_netcdf("test.nc") # fails
new_results.results.to_netcdf("test.nc") # works
```

**Comment by brynpickering** [comment]
See #293
