### ISSUE TITLE
Cannot load v0.6.5 on windows

### ISSUE THREAD

**Issue by FebinKa** [calliope-project/calliope#311]
I was unable to install calliope version 0.6.5 on Windows. I created a virtual environment and specified that it should use python v3.7 and calliope v0.6.5 as it reverts to v0.6.2 otherwise.
``conda create -c conda-forge -n calliope python=3.7 calliope=0.6.5``

However, that code, which seems to work on Linux, returns the error message below on Windows.
``Package python conflicts for:
calliope=0.6.5 -> bottleneck[version='>=1.2'] -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3.6']
python=3.7
calliope=0.6.5 -> python[version='>=3.7,<3.9']
``

I have already tried several things (specifying the bottleneck version as well, loading bottleneck first and then calliope, installing calliope through pip), but none of them have worked and for most, the error message just states that there are faulty specifications without specifying which ones. The installation attempt with pip lead to the following error message:
``ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly``

**Comment by sjpfenninger** [comment]
We should probably remove `bottleneck` from the requirements, as it's entirely optional.

**Comment by sjpfenninger** [comment]
This should be resolved with #319 since it removes `bottleneck` from the requirements
