### ISSUE TITLE
Separate `build` and `run`

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#314]
## Problem description

The current method to load and run a model is as follows:

```python
m = calliope.Model(...)
m.run()
```

This glosses over an intermediate step, in which the mathematical model is built in Python. To overcome this, we have a somewhat hidden method to just build the mathematical model: ```m.run(build_only=True)```.  We use this to to check constraints etc. in our tests, without the computational burden of optimisation. It's also becoming more useful as a method to avoid the overhead of building this Pyomo model several times, allowing a user to instead build the model, change some values in mutable Pyomo objects, then rerun the optimisation:

```python
m = calliope.Model(...)
m.run(build_only=True)

m.backend.update_param(...)
m2 = m.backend.rerun()

m.backend.update_param(...)
m3 = m.backend.rerun()

# etc...
```

This is linked to issues on how we interact with the Pyomo backend (#293, #294).

## Possible solution
We update the process to be:

```python
m = calliope.Model(...)  # we now have the xarray input dataset
m.build()  # we now have the backend model (currently Pyomo)
m.run()  # we not have xarray results dataset
```

Between `build` and `run`, the backend model could be edited, on the understanding that rebuilding the backend model requires `build` to be called, and generating new results requires `run` to be called:

```python
m = calliope.Model(...)
m.update_param(...)  # updates the parameter in the the xarray dataset *only*
m.build()
m.run() 
m.to_netcdf("results_1.nc") 

m.update_param(...)  # updates the parameter in the backend and the xarray dataset
m.run()
m.to_netcdf("results_2.nc") 
```

## Calliope version

0.6.5-dev

**Comment by sjpfenninger** [comment]
Part of backend rewrite in #293
