### ISSUE TITLE
Loading user-defined representative days fails

### ISSUE THREAD

**Issue by leonardgoeke** [calliope-project/calliope#317]
## Problem description

I'm trying to run Calliope with self-defined representative days. For this purpose, I've added the following to the model configuration and tried to run `calliope.Model('calliope_model/model.yaml')`.

```
time:
    function: apply_clustering
    function_options:
        clustering_func: file=test_slice.csv:cluster
```
This produces the following error:

```
  File "<stdin>", line 1, in <module>
  File "D\miniconda3\envs\calliope\lib\site-packages\calliope\core\model.py", line 74, in __init__
    model_run, debug_data = model_run_from_yaml(config, *args, **kwargs)
  File "D\miniconda3\envs\calliope\lib\site-packages\calliope\core\preprocess\model_run.py", line 59, in model_run_from_yaml
    return generate_model_run(
  File "D\miniconda3\envs\calliope\lib\site-packages\calliope\core\preprocess\model_run.py", line 569, in generate_model_run
    process_timeseries_data(config, model_run)
  File "D\miniconda3\envs\calliope\lib\site-packages\calliope\core\preprocess\model_run.py", line 512, in process_timeseries_data
    first_file, first_index = indices[0]
IndexError: list index out of range
```

In the corresponding time-series file the cluster is provided along with the other time-series data:

```
,cluster,demand,wind,solar
2005-01-01 00:00:00,0,-82.72,0.34,0
2005-01-01 01:00:00,0,-80.01,0.43,0
2005-01-01 02:00:00,0,-74.91,0.44,0
```

## Steps to reproduce the problem

Run the added test model: 
[calliope_model.zip](https://github.com/calliope-project/calliope/files/4786318/calliope_model.zip)

## Calliope version

0.6.5 master

**Comment by brynpickering** [comment]
Thanks for the issue @leonardgoeke. We check the consistency of timeseries data, but the clustered data *can* be inconsistent relative to the rest of the data (e.g. hourly timeseries data, but clusters are defined daily). This check is being thrown off by the cluster data being in the same file as the rest of the data. 

We'll fix this in time, but for now you just need the cluster data to be in an independent CSV, with the same index.

**Comment by leonardgoeke** [comment]
Thank you for that very swift and helpful answer!

**Comment by brynpickering** [comment]
No problem! I'm going to reopen the issue, since it's still a bug we should fix :)

**Comment by leonardgoeke** [comment]
I think, I’ve successfully loaded my own representative days. In addition, I’ve also applied my own weighting by manually overwriting `model._model_data.timestep_weights.data`. I’ve added all the corresponding files below.

I would be greatly appreciated, if I could get some quick feedback if read-in and weighting of the representative days is done correctly in my example. I’m working on a publication on time-series reduction and would like to rule out that my results are driven by a read-in error.
[calliope_model.zip](https://github.com/calliope-project/calliope/files/5747228/calliope_model.zip)

**Comment by brynpickering** [comment]
@leonardgoeke sorry for missing this, we don't get priority notifications when not directly pinged with `@`! I will assume that your manual overwriting fits your needs, although I'm surprised that you needed to apply it, since the timestep weights should be set when time clustering is undertaken internally.

Anyway, we're now planning to remove time aggregation functionality from the core Calliope offering, to depend instead on an external module (that we might write, but is more likely to be an external dependency). See #356.
