### ISSUE TITLE
Link sets to supersets

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#322]
## Problem description

This is an internal issue. Currently, there are loads of subsets in the xarray and in Pyomo which aren't defined as such. Making the link explicit may have two benefits:

1) Ability to infer links programmatically.
2) (Maybe) performance improvements.

I am not sure on the latter, as I haven't tested this. But these subsets can easily contain 1000s of elements, and if they were linked in Pyomo, not copied, this may improve performance. 

## Calliope version

0.6.5

**Comment by brynpickering** [comment]
How this would look in pyomo: `backend_model.techs_supply = po.Set(initialize=mapped_techs, domain=backend_model.techs`, where `mapped_techs` is some mapping function applied to the `techs` dim in the xarray dataset.

**Comment by sjpfenninger** [comment]
No longer needed after the set cleanup
