### ISSUE TITLE
Split loc_techs for good

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#323]
## Problem description

There are various issues with the use of the combined sets `loc_techs` and `loc_techs_carrier` -- in particular, it makes analysing the results more complicated. There were two reasons why this was introduced in the first place:

1) Efficiency on the storage side.
2) Efficiency within Pyomo.

The first issue is probably solvable with the [introduction of sparse support into xarray](http://xarray.pydata.org/en/stable/whats-new.html?highlight=sparse#v0-13-0-17-sep-2019). The second may be solvable with [sparse sets in Pyomo](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Sets.html#sparse-index-sets) (but this needs to be investigated further).

## Calliope version

0.6.5

**Comment by brynpickering** [comment]
For why we did this to begin with, see #69
