### ISSUE TITLE
[Info requested] Home Energy Management | Daily Optimisation 

### ISSUE THREAD

**Issue by lblabr** [calliope-project/calliope#340]
I'm would like to use check|test if Calliope may can be used to do the optimisation of my energy assets. 
Due that i have several questions....

I would like to optimise on daily basis, depending on pv-production/forecast the energy storage should be loaded/unloaded. for the demand an energy tariff with happy hour should be used...

i read your detailed documentation but i could not finde how to attach timeintervals to assets or costs / capacities etc... how this is done ?

e.g. costs on demand (umet demand):
0..19:00 25ct/kWh
19:00 - 20:00 13 ct/kWh
20..0:00 25 ct/kWh

happy hour might be used to charge energy storage (without price restrction)
happy hour might be used to charge energy storage (if price is below, grid feed in tariff)

heat pump:
heat pump needs to run 6h/day, when should be defined be optimisation, how this may modeled ? 
 
can the charging power of the energy storage be calculated depending on forecast/net capacity restrictions ?

thanks a lot! thank in advance for your feedback!

Lars

**Comment by brynpickering** [comment]
Hi @lblabr, I'm going to close this as we can't really offer implementation support in our issue tracking. Although I see some of the things you mention as being possible, and some not, I would ask that you ask your questions again on our [Gitter chat channel](https://gitter.im/calliope-project/calliope), where others in the community may also be able to help answer your questions.
