### ISSUE TITLE
`--save_plots` no longer available

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#341]
## Problem description
Since we tried killing plotting and then ultimately let it stay, we forgot to reinstate the CLI option `--save_plots`. This means that a model cannot be run from the command line with that option.

## Steps to reproduce the problem

run `calliope run --save_netcdf=results.nc --save_csv=outputs model.yaml` and see it complain

## Calliope version

0.6.6

**Comment by sjpfenninger** [comment]
😖

**Comment by brynpickering** [comment]
Incorporated in 673e52f23832157f82dbd11939bdbd0d8ab83654
