### ISSUE TITLE
make filename for plotting timeseries configurable

### ISSUE THREAD

**Issue by lblabr** [calliope-project/calliope#343]
## Problem description

i store the results of the optimzation for each run in an own directory. i would like to have the plotted timeseries there to

## Steps to reproduce the problem

model.plot.timeseries()

results in the file: temp_plot.html

i would like to pass an output dir and/or filename

maybe like this:
model.plot.timeseries(filename="20202811/timeseries.html")

## Calliope version

0.6.6 post 1

**Comment by brynpickering** [comment]
Please see the docstring for each plotting function. You can use `to_file="..."` for this purpose.

**Comment by lblabr** [comment]
but to_file does not support html in for plot.timeseries() and i like the html output ;)

workaround inside my python script:

    template_path = os.path.join(
            os.path.dirname(__file__), "plots_template.html"
        )

    with open(template_path, "r") as f:
            html_template = jinja2.Template(f.read())

    html = html_template.render(
            model_name=' ' + model.model_config["name"] + ' - ' + outputDir + ' ',
            calliope_version=model._model_data.attrs["calliope_version"],
            top=model.plot.timeseries(html_only=True),
        )

    with open("./" + outputDir + "/timeseries.html", "w") as f:
        f.write(html)
