### ISSUE TITLE
plot.timeseries function datetime subset does not work well

### ISSUE THREAD

**Issue by CROdominik** [calliope-project/calliope#345]
## Problem description

In postprocessing of results, a plot.timeseries function for datetime subsets does not work if the timesteps are not explicitly expressed.

## Steps to reproduce the problem

For any model.results construct try to plot a subset of timeseries, e.g. one day.

model.plot.timeseries(array = 'electricity', subset={'timesteps':['2018-08-01']})

The abovementioned line produces an empty plot. A current workaround is to explicitly express the timesteps:
model.plot.timeseries(subset={'timesteps': model.inputs.timesteps.loc['2018-08-01'].values}) 

## Calliope version

0.6.6post1

**Comment by sjpfenninger** [comment]
Will be addressed in #357
