### ISSUE TITLE
Unmet demand only in the netcdf results if not 0

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#355]
## Problem description

When `ensure_feasability` is turned on, `unmet_demand` usually gets reported within the netcdf results as a variable with the same name. If unmet demand is 0, [this variable is deleted](https://github.com/calliope-project/calliope/blob/ea89a660742a04c80486fe34a4d8c49e230805ac/calliope/postprocess/results.py#L210).

This behaviour is problematic I think for two reasons. First, it's surprising. For a while I thought I had to calculate unmet demand myself. Second, it makes automatic batch analysis of runs more complicated, as one has to handle the special case `unmet_demand == 0`. Therefore, I suggest to always report `unmet_demand` in the netcdf when `ensure_feasability` is turned on. Maybe even if `ensure_feasability` is turned off. This would be most consistent to me. 

## Steps to reproduce the problem

Run a model with `ensure_feasability: True` which would work without `ensure_feasability`, too.

## Calliope version

0.6.6

**Comment by brynpickering** [comment]
Incorporated in 1a09adebd3252d1a45e88c202314e81681c481f5
