### ISSUE TITLE
`power` energy carrier too ingrained

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#37]
Currently, Calliope works on the assumption that `power` will be an energy carrier in the system. It is sufficiently ingrained that the construction of the solution file will fail if it isn't included. The metadata summary is also only constructed for that one energy carrier. 

In situations where there are multiple energy carriers, the summary is erroneous. In situations where there is no `power` carrier (e.g. giving it the perhaps more apt title `electricity`), Calliope fails after solving the optimisation, but before finishing construction of the solution DataArray. 

There needs to be a cleaner way of dynamically adapting for multiple energy carriers, particularly in ``core.Model.get_summary`` , but I haven't yet worked out how to make it as efficient as the current XArray indexing, as I can only see it being possible by looping over all the technologies.

**Comment by brynpickering** [comment]
reducing priority of this now that a (albeit inelegant) solution exists in commit ff5947b

**Comment by sjpfenninger** [comment]
Closed in 1e9a409 and 33a54d1
