### ISSUE TITLE
Annual fixed O&M costs not included in model if no other investment costs are set

### ISSUE THREAD

**Issue by jmorrisnrel** [calliope-project/calliope#373]
## Problem description

The om_annual constraint doesn't trigger the loc_tech to be added to the loch_techs_investment_costs set meaning that if none of the other investment costs are set for a loc_tech the fixed O&M costs are not factored into the model and are not reflected in the solution.

I've patched in a fix locally to include om_annual/om_annual_fractional_percentage in the loc_techs_investment_costs set (calliope/preprocess/sets.py:447) which resolves the issue. It does potentially create another issue where the model_data_dict["data"]["cost_deprecation_rate"] dictionary used in costs.py:170 isn't set if there are only fixed OM costs in the model and no other investment costs.

## Steps to reproduce the problem

Configure a tech/loc_tech to have an om_annual cost without other annual fixed or capacity costs. The om_annual cost will not be reflected in any of the outputs.

## Calliope version

This bug is present in 0.6.7 but looks like it should be fixed in the new rework of the set definitions in the newer version.

**Comment by jmorrisnrel** [comment]
[OM_bugged.zip](https://github.com/calliope-project/calliope/files/7677851/OM_bugged.zip)
Here is an example model where the CC_Gas_Power_Plant tech will replicate the issue on 0.6.7 and earlier.

**Comment by brynpickering** [comment]
Good catch @jmorrisnrel. Fixed in v0.6.9 which should be available from conda in the coming days.
