### ISSUE TITLE
Expand variable/parameter names

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#40]
For clarity, where applicable, to change names of python variables to more readable values. This applies to parts of the YAML files and of Calliope innards.
e.g. r -> resource

**Comment by willu47** [comment]
👍

**Comment by brynpickering** [comment]
Some of the main offenders:

**sets:**
y: technology
x: location
c: carrier
k: cost class

**costs, constraints & decision variables:**
r: resource
s: storage
e: energy
r2: secondary resource
eff: efficiency
x_map: map location
cap: capacity
c: charge/carrier/constraint
prod: production
con: consumption
om: operation and maintenance
var: variable
frac: annual fraction (relative to e_cap)

In some cases, it's easy enough to simply expand, others would become excessively long-winded. 
Also, some span constraints, decision variables, and parameters, so an easy way of using the same term whilst distinguishing between those would be good. E.g. all caps, first letter caps, no caps; or suffixes `_constraint`, etc.

**Comment by brynpickering** [comment]
Work on this has begun in a [new branch](https://github.com/calliope-project/calliope/tree/Verbose_refactoring). Started with core.py, with the intention of changing the following once reorganisation of base.py and sets have taken place:

y -> tech
x -> loc
c -> carr (I'm still not sure about this one...)
k -> cost
r -> resource
e -> energy
p -> parasitic
c_rate -> charge_rate

Ones expected to stay the same:

eff (efficiency)
cap (capacity)
prod (production)
con (consumption)

Some points for discussion:

* what to do about 'storage', is 'store' good enough?
* var is used to mean a Python/Pyomo variable as well as a parameter/variable that varies in time. Suggested to change time varying things to '_varying', or similar
* No discussion yet on what to do about 'om', 'frac', and 'x_map'

**Comment by sjpfenninger** [comment]
Fixed in 0.6.0
