### ISSUE TITLE
Renaming in math syntax

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#418]
In general, keep names close to what happens with the xarray objects.

Changes:
- [x] Rename all `imask` to `where` in order to closely match xarray syntax
- [x] Remove `equation` in favour of slightly more verbose `equations` at all times
- [x] `components` -> `sub_expressions`
- [x] `index_slices` -> `slices`
- [x] `expression` top level key -> `global_expressions`
- [x] `exists` in techs/nodes -> `active` (to match math formulation)
- [x] `optimisation_config_overrides` / `component_config` -> `custom_math` / `math`

Additions:
- [x] Add `description` key to all math items

**Comment by sjpfenninger** [comment]
> @sjpfenninger is having second thoughts about `global_expressions` to define linear math expressions that can be referenced by name in constraints/objectives. Any additional ideas are welcome.

My second thought was `named_expressions`

**Comment by brynpickering** [comment]
We'll keep `globall_expressions` (for now), so I'm closing this issue.
