### ISSUE TITLE
the result as a html data

### ISSUE THREAD

**Issue by hoomannnnnn** [calliope-project/calliope#473]
## Problem description

_Describe the problem or error here_

If reporting an error when running Calliope on the command line, please re-run your command with the ``--debug`` option, e.g.:

``calliope run my_model.yaml --debug``

Then post the full output from the debug run.

If reporting an error when running Calliope interactively in a Python session, please include a full traceback.

## Steps to reproduce the problem

_Describe the steps needed to reproduce the problem here_

## Calliope version

_What exact version of Calliope are you using?_

**Comment by hoomannnnnn** [comment]
I have a problem with generating `model.plot.summary` in my code. The code runs correctly and completes without errors, but no HTML file is being generated. Its my run model:                                                                                                                      # Imports
import calliope
import warnings
# ignore Future Warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
calliope.set_log_verbosity('INFO', include_solver_output=True)
model = calliope.Model('model.yaml')
model.run()
model.plot.summary(to_file='test4333.html')

**Comment by brynpickering** [comment]
Which version of calliope are you using @hoomannnnnn ? `calliope.__version__` in an interactive session should give it to you. Or `calliope --version` in the command line.

**Comment by brynpickering** [comment]
Closing as I can't reproduce the issue. Feel free to reopen @hoomannnnnn if you are still facing this issue.
