### ISSUE TITLE
Bulk Download for Technologies is not working at Engage

### ISSUE THREAD

**Issue by treyess** [calliope-project/calliope#515]
## Error 500 appears when try Bulk download for Technologies, Locations and nodes is working.

Hello I'm triying to make massive update to my model, speciically for Technologies, I want to include the Fuel cost on all the same type technologies depending regions and capacity factor profiles. I thought the easiest way to do it was using the csv file generate when press Bulk Download, since I did understood that friendly_data is for other proposes. Please indicate if there's a better way to do it. However the button is not working in Engage.

_When click on Bulk Download button in Engage interface, Server Error (500) appears. When you click Bulk Upload button, seems to be working.

**Comment by sjpfenninger** [comment]
This looks like an issue related to Engage, not Calliope. Can you re-open this issue in the [Engage issue tracker](https://github.com/NREL/engage)?

**Comment by treyess** [comment]
Done, thanks a lot!!!
