### ISSUE TITLE
Reading csv solution for single iteration. 

### ISSUE THREAD

**Issue by csv2000** [calliope-project/calliope#52]
I am Vijay from National institute of Advanced Studies, Bengaluru. I am using calliope as the base for my project. I am currently running a single iteration (one configuration) of the model and saving it as csv. 

But I cannot load the entire solution using calliope.read.read_dir('path_to_output'). It raises error while reading iterations.csv 

FileNotFoundError: File b'./5Node_2017_base/iterations.csv' does not exist

Is csv based reading only for multiple iterations? if so, perhaps a check should be added before reading. Or am I missing something?

I am using 0.3.7.

**Comment by sjpfenninger** [comment]
You should use ``calliope.read.read_csv('path_to_output')`` to read a single solution. Can you confirm that this works?

Also, what is the reason for using 0.3.7? I would recommend using the newest version, 0.5.0.

**Comment by csv2000** [comment]
Thank you, that works and loads the utils.AttrDict

I am now making the shift to 5.0 and xarray.

On Mon, Jun 12, 2017 at 3:10 PM, Stefan Pfenninger <notifications@github.com
