### ISSUE TITLE
Model Gallery Link not working

### ISSUE THREAD

**Issue by sstroemer** [calliope-project/calliope#520]
## Problem description

The link ["model gallery" in the Quick Start section](https://github.com/calliope-project/calliope/blob/42975f0abc2587dbb68d2e5e1389e7d547513ade/README.md#L48) of `README.md` currently does not work.
I'm not sure where it should point to, maybe https://www.callio.pe/research/#publications/?

## Steps to reproduce the problem

\-

## Calliope version

commit 42975f0abc2587dbb68d2e5e1389e7d547513ade

**Comment by brynpickering** [comment]
Fixed in #527
