### ISSUE TITLE
s_time.max can't handle varying timestep resolution

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#53]
`s_time.max` is a way to set a maximum storage based on the length of discharge time you want available, rather than setting a capacity limit. The issue with it was that it used a reference efficiency for discharge.

When using a timeseries varying e_eff, it's better to check the situation with worst efficiency, then ensure that your maximum capacity allows discharge over the time periods of that worst efficiency. This update was made in 0.5.0: https://github.com/calliope-project/calliope/blob/master/calliope/constraints/base.py#L387-L427

Currently though, if you change timestep resolution, this function will continue to think that each timestep is worth one unit of time, creating an erroneous result.

**Comment by sjpfenninger** [comment]
Closing, as s_time.max is no longer provided in `0.6.0`
