### ISSUE TITLE
scientific notation for number in yaml files

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#57]
I was trying to use number in scientific notation in the yaml files, but apparently it is read as a string and not a number:

    boiler:
        costs:
            monetary:
                e_cap: 1e3

```=> TypeError: Cannot convert object of type 'str' (value = 1e3) to a numeric value.```

**Comment by sjpfenninger** [comment]
This _should_ be possible in YAML, will investigate.

**Comment by sjpfenninger** [comment]
This is fixed in 4ee6d7c by switching to a different YAML parser library.
