### ISSUE TITLE
adding scenarios and overrides 

### ISSUE THREAD

**Issue by hiddegrootes** [calliope-project/calliope#592]
### What happened?

While adding scenarios and overrides, I experience trouble with the current formulation on the website with for exmaple: model.time_subset: ['2005-01-01', '2005-12-31'] -> It worked when i used config.init.time_subset as inside model it is structered this way. 

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Version

0.7.0-dev

**Comment by irm-codebase** [comment]
@hiddegrootes thanks for reporting this!

We'll implement this fix soon.
