### ISSUE TITLE
debug functionality missing in Model.__init__

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#607]
### What happened?

Calliope's `Model`  class initialization has a debug parameter with the following description:
```
            debug (bool, optional):
                If True, additional debug data will be included in the built model.
                Defaults to False.
```
At the moment, this parameter is completely unused by the code.

We check for `model_data.attrs["_debug_data"]` in other parts of the code, and for now it seems like this functionality won't work at all.

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Version

v0.7

**Comment by brynpickering** [comment]
Yeah, we need to purge that. Debug info is all available via the logger (and you can store that in a file following our tutorial: https://calliope.readthedocs.io/en/latest/examples/calliope_logging/)
