### ISSUE TITLE
Mispaced math documentation guide in pre-defined math

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#622]
### Description

For some reason the guide to math documentation is being appended to the inter-cluster storage math section.

Probably due to previous re-arranging of the docs.

### Related links

- https://calliope.readthedocs.io/en/latest/math/storage_inter_cluster/

### Version

v0.7

### Proposed change

Move this to the "Defining your own math" section?

**Comment by brynpickering** [comment]
No, this is literally a guide to the rendered math as viewed in the documentation (it's talking about bold vs italic script etc.). We prepend this to each of the pre-defined math pages to act as a primer for reading the rendered math.
