### ISSUE TITLE
Wrong "in domain" symbol

### ISSUE THREAD

**Issue by sstroemer** [calliope-project/calliope#652]
### Description

`domain: integer` is rendered as $\forall \mathbb{Z}$, instead of, e.g., $\in \mathbb{Z}$, similar for the variables not having an explicit domain, which show $\forall \mathbb{R}$.

### Related links

- for example: [`flow_cap`](https://calliope.readthedocs.io/en/latest/math/base/#__tabbed_59_1)

### Version

latest (48148b814a8ba0cd64fa9b48decff4b5b60eb0d7)

**Comment by brynpickering** [comment]
Thanks, yeah this was the wrong notation. Is there an agreed notation for domains in defining decision variables in optimisation problems? If it is e.g., ∈ Z, happy to go with that.

**Comment by sstroemer** [comment]
Some references:

- "General form of a mathematical programming model" in _Introduction to Mathematical Programming_, by Ted Ralphs, see slide 7 in lecture 1 [[slides]](https://coral.ise.lehigh.edu/~ted/files/ie406/lectures/Lecture1.pdf)
- "LP standard form", see for example page 55, section 2.1, in _Introduction to Mathematical Programming_, by Michael Kupferschmid [[book](https://ashermath.com/imp.pdf)]
- For a more CS related example, the introduction to LPs by [[jump.dev](https://jump.dev/JuMP.jl/stable/tutorials/linear/introduction/)]
- Less academic, but standard forms for [wiki:LP](https://en.wikipedia.org/wiki/Linear_programming#Standard_form) and [wiki:MILP](https://en.wikipedia.org/wiki/Integer_programming#Canonical_and_standard_form_for_ILPs) _(which shows that the EN version of LP is ... lacking)_

---

In the end it does not really matter as long as it's clear, alternative ways that I can think of right now are:

- $x \in \\{0, 1\\}$ (c.f. [jump.dev](https://jump.dev/JuMP.jl/stable/tutorials/linear/knapsack/#Formulation))
- $x \quad \text{integral}$
- $x \quad \text{binary}$
- $x \quad \text{free}$ (= interpreted as "$x \in \mathbb{R}$ without bounds")
- $x \geq 0$ (= "non-negative and real", because $\geq$ would not work for $\mathbb{C}$)

Most of them however do not explicitly state what's happening, e.g., $x$ may be complex valued, and $foo \in X$ is immediately clear for any $X$ (and also allows more complex formulations, like conic programming, etc.).

**Comment by brynpickering** [comment]
Maybe $\in \mathbb{Z}$ and $\in \mathbb{R}$? We don't have binary variables, only integer ones that can be limited to a maximum of 1 using a parameter. So it'll only be "in set of integers" or "in set of all reals".

**Comment by sstroemer** [comment]
> Maybe ∈ Z and ∈ R ? We don't have binary variables, only integer ones that can be limited to a maximum of 1 using a parameter. So it'll only be "in set of integers" or "in set of all reals".

Sounds great! Maybe (don't know if that is possible) adding the variable before that helps with readability?

For example (`async_flow_switch`) instead of:

```math
\begin{aligned}
& \forall \text{node} \in \text{nodes}, \text{tech} \in \text{techs}, \text{timesteps} \in \text{timesteps} \\
& \in \mathbb{Z}: \\
& \\
& \dots \quad \text{actual content} \quad \dots
\end{aligned}
```

is the following (or something similar) possible?

```math
\begin{aligned}
& \forall \text{node} \in \text{nodes}, \text{tech} \in \text{techs}, \text{timesteps} \in \text{timesteps}: \\
& \\
& async\_flow\_switch_{\text{node},\text{tech},\text{timestep}} \in \mathbb{Z} \\
& \\
& \dots \quad \text{actual content} \quad \dots
\end{aligned}
```
