### ISSUE TITLE
Wording in `flow_cap_min`

### ISSUE THREAD

**Issue by sstroemer** [calliope-project/calliope#653]
### Description

Currently, `flow_cap_min` states

> Limits `flow_cap` to a minimum. NOTE: this will force `flow_cap` to a minimum value unless `cap_method` is set to `integer`. If `cap_method=integer`, this will be scaled by the number of integer units of a technology purchased.

which might be misinterpreted by some users (c.f. the comment posted by @brynpickering in [#643](https://github.com/calliope-project/calliope/issues/643#issuecomment-2272964008)).

### Related links

- [`flow_cap_min`](https://calliope.readthedocs.io/en/latest/math/base/#flow_cap_min)

### Version

latest (48148b814a8ba0cd64fa9b48decff4b5b60eb0d7)

### Proposed change

This acts as lower limit (lower bound) for `flow_cap`. If `cap_method=integer`, this will be scaled by the number of integer units of a technology purchased.

> **Note:**
> 
> If `cap_method = continuous` (which is set by default), then setting `flow_cap_min` to any value greater than `0` forces the model to _always_ respect that limit, preventing it from not investing into the technology. Use this to enforce given investment plans, or to account for existing technologies that cannot be decommissioned.
>
> _An example:_ If `cap_method = continuous` and `flow_cap_min = 100`, then `flow_cap` has to be at least `100`. It going to `0` is **not possible**, unless you switch to `cap_method = integer` (see [`cap_method`](#cap_method)).

**Comment by brynpickering** [comment]
Proposed change sounds good.
