### ISSUE TITLE
Ommit long files from search (schemas)

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#670]
### Description

When searching stuff in the docs, the schema often makes the search hard to use due to its length.

I propose to omit them from the preview of the search bar, at least.

Example (the full length of the schema appears, which I cannot show in one image):

![image](https://github.com/user-attachments/assets/38f410e3-0d35-4c25-878e-fa4c642e63e1)

### Related links

Spammy files
- https://calliope.readthedocs.io/en/latest/reference/model_schema/
- https://calliope.readthedocs.io/en/latest/reference/math_schema/
...

### Version

v0.7.0

**Comment by brynpickering** [comment]
Now that we have parameters defined in the base math, I think it would be fine to exclude the schema. Another option would be to [lower the ranking of the schema in search results](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-boosting).
