### ISSUE TITLE
Renaming `data_sources` to avoid confusion

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#673]
### What can be improved?

@sjpfenninger @brynpickering 

What do you think about renaming of `data_sources.something.source:`?
It's easy to confuse it with `source_use_equals` and similar parameters.

It's even more confusing for for demand, since you have to do `data_sources.demand_timeseries.source: sink-timeseries.csv`.

I propose the following:
- `data_tables.something.file:`
- `tabular_data.something.file:` (if you want to stick to the documentation).

### Version

v0.7

**Comment by brynpickering** [comment]
So, the reason we use `source` and not `file` is because you can [load data directly from in-memory dataframes](https://calliope.readthedocs.io/en/latest/creating/data_sources/#loading-csv-files-vs-pandas-dataframes).  Perhaps: 

- `data_tables.something.table`
- `data_tables.something.data`

?

**Comment by irm-codebase** [comment]
Aha.

I think I like `data_tables.title.data` more. If you want to be really specific, `data_tables.title.dataset`.
