### ISSUE TITLE
Fixing Circular Definitions in Docs

### ISSUE THREAD

**Issue by jeisenman23** [calliope-project/calliope#699]
### Description

This was in the getting familiar with Calliope definitions. These definitions are self referential and relatively difficult to understand without real examples. 

Current:
Technology: a technology that produces, consumes, converts or transports carriers.
Node: a site which can contain multiple technologies and which may contain other nodes for carrier balancing purposes.
Source: a source of commodity that can (or must) be used by a technology to introduce carriers into the system.
Sink: a commodity sink that can (or must) be used by a technology to remove carriers from the system.
Carrier: a carrier that groups technologies together into the same network, for example electricity or heat.

Also, what does "grouping technologies" mean? The example, "electricity or heat" does not constitute a grouping. 

### Related links

https://calliope.readthedocs.io/en/latest/creating/

### Version

v0.7.0

### Proposed change

I propose that each definition should not be self referential and also have a tangible example. One definition may be:

Technology: an entity that produces, consumes, converts or transports carriers.
- You could, for instance, define a solar technology to produce, battery to cosume energy...

**Comment by brynpickering** [comment]
Thanks @jeisenman23 !

I agree that examples would be worthwhile. Would a graphic like this also help?

![image](https://github.com/user-attachments/assets/3f9a3361-4738-487f-a482-4022aeaabdc3)
