### ISSUE TITLE
Pyomo testcase failure with newest gurobi version 12.0.0

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#710]
### What happened?

It seems like  `gurobi` version (12.0.0) is not interacting well with one of our test cases (**test_no_duplicate_log_message**), leading to CI issues.

Downgrading `gurobi` to an 11.x.x version will solve the issue, but it is not ideal since our installation requirements do not enforce those versions, and most people will move their licenses to the newest version anyhow.

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Version

v0.7.0dev5

### Relevant log output

```Shell
============================================================================== FAILURES ==============================================================================
_____________________________________________________________ TestLogging.test_no_duplicate_log_message ______________________________________________________________
[gw2] linux -- Python 3.12.7 /home/ivanruizmanuel/miniforge3/envs/calliope/bin/python3.12

self = <tests.test_backend_pyomo.TestLogging object at 0x7f8aab665970>, caplog = <_pytest.logging.LogCaptureFixture object at 0x7f8aaa29d1f0>
gurobi_model = <calliope.model.Model object at 0x7f8aaa257a10>

    def test_no_duplicate_log_message(self, caplog, gurobi_model):
        caplog.set_level(logging.DEBUG)
>       gurobi_model.solve()

tests/test_backend_pyomo.py:1590: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/calliope/model.py:407: in solve
    results = self.backend._solve(warmstart=warmstart, **solver_config)
src/calliope/backend/pyomo_backend_model.py:311: in _solve
    results = opt.solve(self._instance, tee=True, **solve_kwargs)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_solver.py:130: in solve
    self._presolve(*args, **kwds)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_solver.py:68: in _presolve
    self._set_instance(model, kwds)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py:472: in _set_instance
    self._add_block(model)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py:490: in _add_block
    DirectOrPersistentSolver._add_block(self, block)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_or_persistent_solver.py:229: in _add_block
    self._add_constraint(con)
../../../miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py:546: in _add_constraint
    gurobipy_con = self._solver_model.addConstr(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: addConstr() got an unexpected keyword argument 'sense'

src/gurobipy/_model.pyx:3894: TypeError
```

**Comment by irm-codebase** [comment]
## Further debugging

If you update pyomo to `6.8.0`, keeping gurobi `12.0.0`, the error changes.

```
./tests/test_backend_pyomo.py::TestLogging::test_no_duplicate_log_message Failed: [undefined]pyomo.common.errors.ApplicationError: No Python bindings available for <class 'pyomo.solvers.plugins.solvers.gurobi_direct.GurobiDirect'> solver plugin
self = <tests.test_backend_pyomo.TestLogging object at 0x7fafdac68560>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fafd61f53a0>
gurobi_model = <calliope.model.Model object at 0x7fafd681e000>

    def test_no_duplicate_log_message(self, caplog, gurobi_model):
        caplog.set_level(logging.DEBUG)
>       gurobi_model.solve()

tests/test_backend_pyomo.py:1590: 
```

The source of the issue is now `override_dict={"config.solve": {"solver": "gurobi", "solver_io": "python"}}`.
For some reason, using `solver_io = python` causes pyomo to "forget" gurobi is a thing????

So, solving this issue could be as simple as removing that specific configuration from our test case, but this could indicate a larger problem... thoughts @brynpickering ???

**Comment by irm-codebase** [comment]
Further debugging makes me suspect that this issue stems from `pyomo` itself or the newest `gurobipy` version.
I've created an issue on the pyomo side to track this https://github.com/Pyomo/pyomo/issues/3414

**Comment by irm-codebase** [comment]
The pyomo team was quite quick replying!
This should be solved with pyomo 6.8.1.

The solution is then to lock pyomo to said version in our `base.txt` file.

**Comment by irm-codebase** [comment]
@brynpickering issue here is that gurobi is not part of our 'core' `base.txt` libraries.
I suggested locking to the newest `pyomo` because it feels like the long term solution, given that we are still in development for v0.7 (and honestly because I've started to see upper locks as [more harm than good](https://iscinumpy.dev/post/bound-version-constraints/))

Once pyomo 6.8.1 is out (soon https://github.com/Pyomo/pyomo/issues/3414#issuecomment-2474515910), I'll test for both gurobi 11 and 12. Most likely it'll work for both (or I hope it does).

If it does not, we can decide on an approach :+1:

**Comment by brynpickering** [comment]
Interesting read, thanks for linking it. We capped pyomo because it was breaking for us and although I tend to agree with the arguments that capping can be harder to deal with than not, the reality is that we have users on the edge of understanding python packaging (i.e., they don't understand it at all) and they just won't do custom pinning if a new release breaks something in calliope. Instead, they will say the package is broken and potentially stop using it. We can't yet move quickly enough to respond to issues introduced by breaking changes in dependencies, we just don't have the contributor numbers...

**Comment by irm-codebase** [comment]
Regarding pyomo: I tested with the newest version, and only one test case gave me trouble (the one that will go away with the update). Whatever was breaking things is gone (at least in my distribution).

Regarding our versioning, although I agree that we cannot respond quickly enough to breaking changes (i.e., I think it's fine to keep our top pins). I think locking gurobi won't be necessary, let's see what happens after pyomo updates.
