### ISSUE TITLE
Error with plot_carrier_production for gas

### ISSUE THREAD

**Issue by louischaman** [calliope-project/calliope#74]
calliope.analysis.plot_carrier_production(solution=model.solution, carrier = "gas")

gives error:

pandas/src/hashtable_class_helper.pxi in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)()

KeyError: 'demand_gas'

**Comment by brynpickering** [comment]
At the moment, you can't plot the output of a given carrier using, internal Calliope functions, if you don't have a set demand for that carrier. in this case `gas` is an intermediate carrier, which isn't part of the set of demands in the system.

I'll update this to not cause an issue in the next release.
