### ISSUE TITLE
Time varying  demand is ignored after 24 h

### ISSUE THREAD

**Issue by miraStud** [calliope-project/calliope#75]
Hallo!
My modell has time varying demand input files, which get to an constant value after 48 hours and my intention was to only optimize the first varying 48 hours. In the result-files the demand for the first 24 hours is correct, but from the 25th hour on the modell takes the constant value.

I build my modell from the build-in-examples and I use the plan-mode. The time-subset is ['2017-01-01', '2017-01-02']

Do you have any idea, what the problem could be?

**Comment by miraStud** [comment]
To make my issue #75 more clear, I want to show you my demand files for heat and power and the results. My model combines the energy carriers gas, power and heat and in this simple example all costs should be ignored - I only wanted to see if the modelling of more than one carrier works.
This is what my heat demand file looks like:
![grafik](https://user-images.githubusercontent.com/33147228/32161143-cd52f9ea-bd54-11e7-9bf2-eafee80201da.png)
This is the result, where all the heat demand should be covered from a chp (combined heat and power plant)
![grafik](https://user-images.githubusercontent.com/33147228/32161282-410a9bea-bd55-11e7-85fa-61cb1188ed44.png)

The power demand has the same course as the heat demand with a offset of 170.
The result for the electricity optimisation:
![grafik](https://user-images.githubusercontent.com/33147228/32161478-f103c2ba-bd55-11e7-89e8-9dea7c7e6eb3.png)

As you can see in the results, the true demand is ignored after 24 hours.
_____________________________________
My techs-file:
techs:
    supply_gas:
        name: 'Natural gas import'
        parent: supply
        carrier: gas
        constraints:
            r: inf
            e_cap.max: 2000
##-Renewables-##
    pv:
        name: 'Solar photovoltaic power'
        color: '#99CB48'
        stack_weight: 100
        parent: supply
        carrier_out: power
        constraints:
            r: file
            e_eff: 1
            e_cap.max: 100
            r_area.max: 1500
    wind:
        name: 'Wind power'
        color: '#838b8b'
        stack_weight: 100
        parent: supply
        carrier_out: power
        constraints:
            r: file
            e_eff: 1 #0.50
            e_cap.max: 100
            r_area.max: 1500
# Conversion
    chp:
        name: 'Combined heat and power'
        stack_weight: 100
        parent: conversion_plus
        export: false
        primary_carrier: power
        carrier_in: gas
        carrier_out:
            power: 0.4
        carrier_out_2:
            heat: 0.32
        constraints:
            e_cap.max: 1000
##-Storage-##
    battery:
        name: 'Battery storage'
        color: '#DC5CE5'
        parent: storage
        carrier: power
        constraints:
            e_cap.max: 100
            s_cap.max: 100
            e_eff: 0.97
            s_loss: 0 
        costs:
            monetary:
                s_cap: 0.01
    boiler:
        name: 'Heat storage'
        color: '#DC9CE1'
        parent: storage
        carrier: heat
        constraints:
            e_cap.max: 100
            s_cap.max: 100
            e_eff: 0.92
        costs:
            monetary:
                s_cap: 0.01
##-DEMAND-##
    demand_power:
        name: 'Electrical demand'
        parent: demand
        carrier: power
    demand_heat:
        name: 'Heat demand'
        parent: demand
        carrier: heat
    unmet_demand_power:
        name: 'Unmet electrical demand'
        parent: unmet_demand
        carrier: power
    unmet_demand_heat:
        name: 'Unmet heat demand'
        parent: unmet_demand
        carrier: heat
_________________________________________
My run file:
name: "Test Run InstaMod"
model: 'model_config/model.yaml'
output:
    format: csv
    path: 'Output1'
mode: plan
solver: gurobi

subset_y: [] 
subset_x: [] 
subset_t: ['2017-01-01', '2017-01-02'] 

debug:
    keep_temp_files: false
    symbolic_solver_labels: false
 ____________________________________
The locations file

locations:
    X1:
        techs: ['pv', 'wind', 'chp',
         'supply_gas', 'battery', 'boiler',
         'demand_power', 'demand_heat',
         'unmet_demand_power', 'unmet_demand_heat']
        available_area: 50000
        override:
            demand_power.constraints.r: file=demand_power1.csv
            demand_heat.constraints.r: file=demand_heat1.csv

I hope that helps understanding my problem.

**Comment by brynpickering** [comment]
Could you check two things for me? 

1. What is the result of plotting the demand when you load the model? use the command `model.data.r.loc[dict(y='demand_heat', x='X1')]` to get the demand data as loaded from csv.
2. Is your 'set_t.csv' file set to the timestamp 'YYYY-MM-DD hh:mm:ss'?

**Comment by miraStud** [comment]
Hello Bryn,

I checked my 'set_t.csv' file and I found the mistake. The time format was
in the German default setting, that why it didn't work. Thank you very
much, that problem was bothering me for several days now.

Best wishes
Gerhild


2017-10-30 13:10 GMT+01:00 Bryn Pickering <notifications@github.com>:

**Comment by brynpickering** [comment]
Glad to hear it's sorted. We'll ensure in an upcoming release that the error is captured at some point in loading the model!
