### ISSUE TITLE
Error while running a big model

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#79]
Hello,

I am running a model with 26 locations and 20 technologies over 8784 hours. The preprocessing was successful but an error appears while solving the model:
```
Error in run command:
CRITICAL Solver output:
Error in run_command:
local variable 'th' referenced before assignment
Calliope run aborted due to an error. Elapsed: 23838.2 seconds (time at exit: 2017-11-09 22:37:19)
```
Because the model is working well for much smaller timesteps, I am suspecting a lack of memory. But it is maybe something else.

Thanks for your help!
Arnaud

**Comment by sjpfenninger** [comment]
Yes, it seems like perhaps the solver runs out of memory. Do you have an indication of what memory usage looks like during the run?

**Comment by sjpfenninger** [comment]
Assuming you are using ``calliope run`` , can you re-run with ``calliope run --debug`` so we see more output on what's going wrong?

**Comment by arnaud-leroy** [comment]
Thanks!
No, I don't have a precise way to measure the memory consumption on that server during the run. But I will run it with --debug to have more information.

At the same time, we are trying to increase our available memory. I think another solution may be to use a lower timestep (every 2 or 3 hours).

**Comment by arnaud-leroy** [comment]
I suspect it is due to the memory, because the model worked at higher time-step

**Comment by sjpfenninger** [comment]
This is definitely a memory issue causing Pyomo to fail, which to some extent we can do nothing about when models get really large (though 0.6.x improves things). Closing this as we are tracking that general issue in #69.
