### ISSUE TITLE
Installed capacity when uniform downsampling the data

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#80]
Hello,

I am testing the uniform downsampling of data because my model is too big too be optimized at an hourly time-step. 
I am a bit confused because some technologies see their fixed installed capacity reduced with higher time-step. The final installed capacity is the initial installed capacity at an hourly time-step divided by the length of the time step.
So if at an hourly time-step the fixed installed capacity is 100, it becomes 50 at a 2h time-step, 33 at a 3h time-step, and 17 at a 6h time-step.

However this is not appearing for technologies with no fixed capacity or for fixed capacity when downsampling with k-means or the heuristic method.

So I suspect that their is an error in the downsampling

**Comment by brynpickering** [comment]
In your results, is demand aggregated correctly per timestep (e.g. model.solution.e.loc[dict(y='demand_power')] shows 2x demand when using a 2h resample)? 

time resolution of each time step (i.e. 1 when time step is 1h, 2 when time step is 2h, etc.) is used in the constraints as a way of increasing the amount of production/consumption that is allowed in any time step, e.g. ``c_prod <= time_res.at[t] * m.e_cap[loc_tech] * p_eff``. So if demand has been doubled by using 2h time steps then c_prod can also be doubled for the same value of e_cap.

**Comment by arnaud-leroy** [comment]
At a 6h resample, my demand at h=0 is the sum of the six first hours. So it seems to work well for the demand. 
The demand "capacity" of the results is also decreasing slightly with higher time-step (-20% at a 6h time-step in comparison with 1h time-step), but I am sure it is normal and due to the averaging.

In the end every results are making sense except the supplies defined by `r`, such as
In techs:
```
  supply_Biogas:
    carrier: gas
    color: '#7f9678'
    constraints:
      e_cap.max: .inf
    costs:
      monetary:
        om_fuel: 0.06
    name: Biogas production
    parent: supply
```

In locations:
```
  South_tyrol:
    override:
      supply_Biogas.constraints.r: 12000.0
      ...
    techs:
      ...
```
In the results:
For a 1h time-step: the installed capacity is 12000
For a 2h time-step: the installed capacity is 6000
For a 3h time-step: the installed capacity is 4000
For a 6h time-step: the installed capacity is 2000

Maybe this r value is not multiplied by the duration of the time-step?

**Comment by brynpickering** [comment]
Looks like it wasn't collecting the correct value for static resource values (as the associated technology wouldn't fit in the the criteria given in `calliope.constraints.base.get_constraint_param`). I'll update it in the master branch, but a current workaround is to create a csv file of timeseries data with constant values for that static resource value.
