### ISSUE TITLE
data not being read correctly

### ISSUE THREAD

**Issue by abart89** [calliope-project/calliope#84]
Hi everyone,

I am trying to model a district energy system with 4 energy carriers and 4 locations with a total of 25 technologies. 
I am currently doing some short runs via the timespan subset command in the run file to test the model. The run goes smoothly but when I plot the timeseries for each carrier I see positive demand values where such should be zero.
In my case for the two carriers "heat" and "cool" while analyzing a winter period (where cool demand in 0) I still get plotted positive values of cool demand; and vice versa happens in a summer period.
I've checked the .csv files and they appear to be fine, heat demand is 0 for whole months in the summer and the same happens for cool demand in the winter.

Thanks in advance for the help!

Andrea

**Comment by brynpickering** [comment]
Hi Andrea, the loaded timeseries data is in ``model.data``. Try looking at that to see if the demand data has been imported from CSV correctly

**Comment by abart89** [comment]
Hello Bryn,

I managed to find the error, while formatting my "set_t" data excel accidentally put "\" instead of "-" as separator in the date. 

Thanks  anyway!
