### ISSUE TITLE
Connecting carrier of one tech to resource of another

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#9]
output of one technology acts as the input of another (e.g. heat for the production of cooling, electricity for the production of Hydrogen). Resource availability for the secondary technology will then depend on production by the primary technology (and any transmission between the two).

**Comment by brynpickering** [comment]
This functionality could directly relate to issue #6 as energy export is a function of the energy produced by the relevant technologies. In this case, the secondary technology is simply the grid which gives you money instead of another type of energy.

**Comment by sjpfenninger** [comment]
Don't we already allow that though? I guess the implicit terminology right now is: resources come from outside the model, and carriers are within the model. So a generation technology turns a resource into a carrier, say heat, and a conversion technology could consume the heat and output cooling.

What parts of the puzzle are currently missing? Explicitly specifying the losses bringing heat from the production to the conversion technology, if they are in the same location?

**Comment by brynpickering** [comment]
Yes, having played around with it, the basic functionality is there. The nomenclature is a little confusing, as you would think of a chiller plant as a supply rather than conversion system (or perhaps more rightly, they are all conversion systems!). Perhaps simplicity could be provided if rather than `conversion` there is just the option to define `r` as the output of another technology for `supply`. This issue links to some extent with issues #8 and #10 as it could mean the defining of a fuel type for each supply technology, for some of those fuel types this would be what is currently defined as `source_carrier`, but all rolled into a newly defined `resource`.

RE losses on bringing heat to the conversion technology, that can be dealt with by creating a dummy location to which the heat needs to be sent via transmission line before it is returned to the conversion technology (with an intermediary conversion technology at the dummy location turning `waste_heat` into `recovered_heat`). It's messy, but works for now.

I'd make this a low priority problem, moving concurrently with issue #10: more on clarity of YAML file than functionality of program.

**Comment by brynpickering** [comment]
Functionality exists for this, and expected updates for version 0.5.0 will overcome the need to create dummy technologies. In providing a `conversion_plus` tech, there will be the functionality to describe the multiple possible inputs and outputs (and how they interact with each other) for a single conversion technology.
