### ISSUE TITLE
Implement epic poetry

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#99]
## Problem description

Given that Calliope is the [muse of epic poetry](https://en.wikipedia.org/wiki/Calliope), we should implement the serialisation of models as epic poems, or at least the representation in poetic form of key model results.

## Steps to implement a solution

* [ ] Find a library for computer-generated poetry, or write the necessary functionality
* [ ] Add poem-emitting functionality to the ``io`` module

**Comment by brynpickering** [comment]
https://github.com/schollz/poetry-generator
https://github.com/kmt901/Poetry-Generator
